### ISSUE TITLE
Can we use real user-agent instead of fake one?

### ISSUE THREAD

**Issue by wojczitsu** [TheM4hd1/SwiftyInsta#10]
Right now library is using always fake user-agent (Samsung C660). Can we use real one from device?

**Comment by TheM4hd1** [comment]
It's possible now to pass your own request headers or turn the default user-agent off.
It's accessible from: ```HttpSettings.shared.useFakeUserAgent = false```

**Note: a user agent is automatically provided as part of the default session configuration but it's awful, better to use your own customized one.**

[Read this link for more details](https://stackoverflow.com/questions/36379347/does-nsurlsession-send-user-agent-automatically)

**Comment by wojczitsu** [comment]
When I set `useFakeUserAgent = false` I get error 'CSRF token missing or incorrect'. Please help :)

**Comment by TheM4hd1** [comment]
I took a look and it seems Instagram **validates** your user-agent before giving you a CSRF token.
User-Agent should follow this format:

```text
Instagram [AppVersion] [OS] ([OSVersion]/[OSRelease]; [DPI]; [DeviceResolution]; [DeviceBrand]; [DeviceModel]; [DeviceModel]; [DeviceModelBoot]; [UserLocale]; [Facebook User-Agent escape string])
```

```text
Instagram 78.0.0.9.103 Android (21/5.0.2; 480dpi; 1080x1776; Sony; C6603; C6603; qcom; ru_RU; 95414346)
```

It takes time to create a random user-agent generator but I think I will probably implement it.
There is a list of devices with info which you can create your own customized user-agent for now.
take a look at ```AndroidDeviceGenerator.swift```

**Comment by TheM4hd1** [comment]
for now, you can use ```CustomUserAgent``` model to create your own user-agent like this:
```swift
let userAgent = CustomUserAgent(apiVersion: "79.0.0.0", osName: "iOS", osVersion: "12", osRelease: "1.4", dpi: "458", resolution: "2688x1242", company: "Apple", model: "iPhone11,2", modem: "intel", locale: "en_US", fbCode: "95414346")
HttpSettings.shared.addValue(userAgent.toString(), forHTTPHeaderField: "User-Agent")
```

If there is no further question, please close the issue.

**Comment by cprovatas** [comment]
@TheM4hd1 
FYI:
`let userAgent = CustomUserAgent(apiVersion: "79.0.0.0", osName: "iOS", osVersion: "12", osRelease: "1.4", dpi: "458", resolution: "2688x1242", company: "Apple", model: "iPhone11,2", modem: "intel", locale: "en_US", fbCode: "95414346")`

won't work outside of framework scope because synthesized initializer is set to internal access by default

**Comment by TheM4hd1** [comment]
use the latest update.
https://github.com/TheM4hd1/SwiftyInsta/blob/28b544577cf4dbb22048f4bfa397364664ac6b72/SwiftyInsta/Classes/Models/CustomUserAgent.swift#L24
As you see the initializer is ```public```

**Comment by TheM4hd1** [comment]
@cprovatas 
Here is a function for creating user-agent base on device.

```swift
public static func build() {
        let device = HandlerSettings.shared.device!
        let apiVersion = "85.0.0.21.100"
        let os = "Android"
        let version = device.frimwareFingerprint.split(separator: "/")[2].split(separator: ":")[1]
        let androidVersion = AndroidVersion.fromString(versionString: String(version))
        if let androidVersion = androidVersion {
            let _androidVersion = androidVersion.versionNumber.split(separator: ".").first!
            let _androidRelease = androidVersion.versionNumber.split(separator: ".").last!
            let dpi = "640dpi"
            let res = "1440x2560"
            let company = device.deviceBrand
            let model = device.deviceModel
            let modem = device.deviceModelBoot
            let locale = "en-US"
            let fbCode = "146536611"
            let agent = CustomUserAgent(apiVersion: apiVersion, osName: os, osVersion: String(_androidVersion), osRelease: String(_androidRelease), dpi: dpi, resolution: res, company: company, model: model, modem: modem, locale: locale, fbCode: fbCode)
            HttpSettings.shared.addValue(agent.toString(), forHTTPHeaderField: Headers.HeaderUserAgentKey)
        }
    }
```

But I doubt that the issue is relevant to user-agent.
