### ISSUE TITLE
How to source users media

### ISSUE THREAD

**Issue by trentona** [TheM4hd1/SwiftyInsta#103]
After this
```swift
let handler = APIHandler()
handler.authenticate(with: .cache(cache)) { _ in
    /* do something here */
```

How do I grab the users media urls? 
I have tried doing handler.(everything I can think of) and im just not getting anything. And if I just print(handler.media) it actually prints out "handler.media"
Im probably just missing something simple, but from the docs and trying every word combo I could think of, I cant figure it out, thanks.

**Comment by TheM4hd1** [comment]
you can access `media` related function via `handler.media`
for example:
```swift
let user: User.Reference = .me /* user */
handler.media.by(user: user, with: .everything, updateHandler: nil) { (res, pagination) in
    switch res {
    case .success(let media):
        let urls = media.compactMap { $0.content.thumbnails.first?.first?.url }
    case .failure(let err):
        print(err)
    }
}
```

**Comment by trentona** [comment]
Thank you. What would go in the for the /* user /*? Its claiming my use is ambiguous and im not sure  how to pass it my users information

**Comment by TheM4hd1** [comment]
check the `User.Reference`, you can pass the `userPK` or `username` to it.

**Comment by trentona** [comment]
How would I pass "sampleusername" to  
let user: User.Reference = "sampleusername"

it doesnt want a string and I dont know what what userPK is
