### ISSUE TITLE
'User' is ambiguous 

### ISSUE THREAD

**Issue by trentona** [TheM4hd1/SwiftyInsta#104]
My last question was closed before it was answered. I cant pass the username because it doesnt want a string and I dont know what userPK is. Could you please instruct me on a complete function. I just want all the urls but it wont accept anything I put in for the user information.

     let user: User.Reference = "sampleUserName"
This isnt working and I have no idea what kind of data it wants

 func printMyStuff() {
    
    guard let key = UserDefaults.standard.string(forKey: "current.account") else { return print("`key` not found.") }
// recover the safely persisted `Authentication.Response`.
guard let cache = Authentication.Response.persisted(with: key) else { return print("`Authentication.Response` not found.") }
// log in.
let handler = APIHandler()
handler.authenticate(with: .cache(cache)) { _ in
print (key)
    /* do something here */

    // var user = handler
     let user: User.Reference = "sampleUserName"
        handler.media.by(user: user, with: .everything, updateHandler: nil) { (res, pagination) in
            switch res {
                case .success(let media):
                    let urls = media.compactMap { $0.content.thumbnails.first?.first?.url }
                
                case .failure(let err):
                    print(err)
                }
            }
    
    
    
    }

        
       

    
    }

**Comment by TheM4hd1** [comment]
because you are using it in a wrong way.
as I said before and you see in the code user must be type of `User.Reference`, not a string.
check the `User.Reference.init` functions to see how pass `string` as username to it.

**Comment by trentona** [comment]
My apologies, I do not know how to "check" User.Reference.init. When I hit look up it just sends me to the back code but Im not too sure what to do with it. Could you please show me the correct way to reference the user, or instruct me further or where and how to "check" it?

**Comment by TheM4hd1** [comment]
man these are basic questions. how do you define an object in swift?
`let user: User.Reference = .username("sampleusername")`

**Comment by trentona** [comment]
Its still saying " 'User' is ambiguous for type lookup in this context ". I have copied exactly what you have said. I have tried putting it on its own and changing where its nested but no matter what I am getting that error. Heres a screen shot. Maybe Im missing something else?

<img width="744" alt="Screen Shot 2019-09-22 at 2 27 18 PM" src="https://user-images.githubusercontent.com/1361081/65394636-2f721b80-dd45-11e9-8f97-56a4a6b10fed.png">

**Comment by TheM4hd1** [comment]
do you have another `User` model in your app? `struct` or `class` ?

**Comment by trentona** [comment]
Oh, Firebase does. If I go to "userResponse.swift" and change your "User" struct to "UserS" for example will that fix it? Will I need to go else where as well?

**Comment by TheM4hd1** [comment]
no need to change, use the namespace
`let user: SwiftyInsta.User.Reference = .username("sampleusername")`

**Comment by trentona** [comment]
thankyou! I didnt know I could do that. "urls" is printing out as "weakObjectReleased". Is that meant to happen?

**Comment by trentona** [comment]
I used "let user: SwiftyInsta.User.Reference = .primaryKey(Int(key)!)" and it worked. Thank you very much for your help
