### ISSUE TITLE
Friendship status is not working

### ISSUE THREAD

**Issue by swifty-things** [TheM4hd1/SwiftyInsta#107]
Today i realized that friendshipStatus is not working **anymore** with the `Invalid response. 405` error code.

Reason for that might be `.get .post` methods. Because there are 2 types of getFriendshipstatus code one using `.get` and other (_which is commented not used at the moment_) using `.post`.

**Comment by TheM4hd1** [comment]
It seems `friendship` endpoint is deprecated, we will analyze it.
for now you can use the `handler.users.user` to receive user info and use `user.rawResponse.friendshipStatus` to access `friendship`

we will release a fix soon as possible, also the old method(the one you said commented) it was unavailable for a while and it seems it's working again.

**Comment by sbertix** [comment]
It only uses `get` on declaration, but the request helper actually overrides it with `post`, since it has a body (because of the changes they made for iOS 13), so that's not the issue.

It probably has to do with the endpoint itself, but if the other one works again, we can switch to that 😊💪

**Comment by anonrig** [comment]
Any update on this? @TheM4hd1

**Comment by swifty-things** [comment]
Yup it works now. But there is still one problem.  
Here is the json form of the friendship status
```
{
  "following" : true,
  "incomingRequest" : false,
  "isBestie" : true,
  "isPrivate" : true,
  "isRestricted" : false,
  "outgoingRequest" : false
}
```
Can't recevie followedBy. I think instagram changed the structure

**Comment by TheM4hd1** [comment]
true, I was able to fix the old endpoint.
example received data:
```json
{"blocking": false, "followed_by": false, "following": true, "incoming_request": false, "is_bestie": false, "is_blocking_reel": false, "is_muting_reel": false, "is_private": false, "is_restricted": false, "muting": false, "outgoing_request": false, "status": "ok"}
```

a fix will release soon.

**Comment by swifty-things** [comment]
@sbertix  @TheM4hd1  Just updated to 2.1.7. Still can't get `isFollowingYou` am i doing something wrong? What could be the problem? 

By the way incoming json data is still the same 
```
 {
  "following" : true,
  "incomingRequest" : false,
  "isBestie" : false,
  "isPrivate" : true,
  "isRestricted" : false,
  "outgoingRequest" : false
}
```

**Comment by TheM4hd1** [comment]
which function are you using?

**Comment by swifty-things** [comment]
> which function are you using?

`handler.users.friendshipStatus(withUser: <#T##User.Reference#>, completionHandler: <#T##(Result<Friendship, Error>) -> Void#>)`

**Comment by swifty-things** [comment]
any news on that? @TheM4hd1

**Comment by TheM4hd1** [comment]
it's fine, make sure to clean build project and build it again.


```swift
handler.users.friendshipStatus(withUser: .username("apple")) { (res) in
     print(try! res.get())
}
// output
// Friendship(rawResponse: SwiftyInsta.DynamicResponse.dictionary(["blocking": SwiftyInsta.DynamicResponse.number(0), "muting": SwiftyInsta.DynamicResponse.number(0), "isRestricted": SwiftyInsta.DynamicResponse.number(0), "incomingRequest": SwiftyInsta.DynamicResponse.number(0), "isPrivate": SwiftyInsta.DynamicResponse.number(0), "isBlockingReel": SwiftyInsta.DynamicResponse.number(0), "status": SwiftyInsta.DynamicResponse.string("ok"), "following": SwiftyInsta.DynamicResponse.number(1), "isMutingReel": SwiftyInsta.DynamicResponse.number(0), "isBestie": SwiftyInsta.DynamicResponse.number(0), "followedBy": SwiftyInsta.DynamicResponse.number(0), "outgoingRequest": SwiftyInsta.DynamicResponse.number(0)]))
```

**Comment by sbertix** [comment]
Or just update to the last version of `SwiftyInsta` if you're still using an old one 😊 @swifty-things

**Comment by swifty-things** [comment]
after 
```
pod deintegrate
pod clean
pod install
```
It downloaded `SwiftyInsta (2.1.6)`

And it's still not working.

**Comment by TheM4hd1** [comment]
`2.1.7` is latest version
run `pod update` to update repo and installing latest version.
