### ISSUE TITLE
Getting error in Image upload

### ISSUE THREAD

**Issue by mehroozkhan** [TheM4hd1/SwiftyInsta#111]
When I try to upload image it gives me an error , but image uploaded successfully on instagram.

My code : 
let picture = Upload.Picture(image: image, caption: caption, size: image.size)
        guard let handler = apiHandler else {
            completion(false)
            return
        }
        handler.media.upload(photo: picture) { (result) in
            switch result {
            case .success ( _):
                completion(true)
            case .failure(let error):
                print(error.localizedDescription)
                completion(false)
            }
        }

Error: 
typeMismatch(Foundation.Data, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "media", intValue: nil)], debugDescription: "Expected to decode Data but found a dictionary instead.", underlyingError: nil))

Is there any quick fix for it ?

**Comment by sbertix** [comment]
Please check #106.
Closing for being a duplicate.
