### ISSUE TITLE
How to get mediaId from Url or permalink

### ISSUE THREAD

**Issue by trentona** [TheM4hd1/SwiftyInsta#112]
I cant seem to find how to get the mediaId, in order to grab the comments and likes. Could you please clarify on "(as represented in Media.identity.identifier!)" from the previous thread. 

// Past comment
ok, cool thank you that makes sense. I only have the permalink though, how do I get the mediaId?
@sbertix

_Originally posted by @trentona in https://github.com/TheM4hd1/SwiftyInsta/issues/34#issuecomment-537627451_

**Comment by TheM4hd1** [comment]
the `media_id` can retrieve from `handler.media.by`
we do not provide a function to convert permalink to media_id

```swift
handler.media.by(user: .username("sampleusername"), with: .everything, updateHandler: nil) { (result, pagination) in
    switch result {
    case .success(let medias):
        print(medias.first?.identity)
    case .failure(let err):
        print(err)
    }
}
```
