### ISSUE TITLE
Ask about credentials.code

### ISSUE THREAD

**Issue by rmelnik7777** [TheM4hd1/SwiftyInsta#115]
Hello, 
Please, tell me. I have a problem.

With  request in func login, I get an SMS with the code, that I registered in credentials.code = "121332". 
I can’t send this code back. How to do it? What am I doing wrong?

This is my code 

class ViewController: UIViewController {

    let handler = APIHandler()    
    override func viewDidLoad() {
        super.viewDidLoad()
        login()
    }
    
    func login() {
        var credentials = Credentials(username: "username", password: "password", verifyBy: .text)
        credentials.code = "121332"
        
        handler.authenticate(with: .user(credentials)) { [weak self] in
            switch $0 {
            case .success(let response, _):
                print("Login successful.")
                guard let key = response.persist() else { return print("`Authentication.Response` could not be persisted.") }
                UserDefaults.standard.set(key, forKey: "current.account")
                UserDefaults.standard.synchronize()
                
                self?.getCurrentUser()
            case .failure(let error):
                if error.requiresInstagramCode {
                } else {
                }
            }
        }
    }

    func getCurrentUser() {
        self.handler.users.user(.me) { ( result: Result<User?, Error>) in
            switch result {
            case .success(let user):
                let username = user?.name ?? "John Doe"
                print("success, username: \(username)")
            case .failure(let error):
                print("failure, error: \(error.localizedDescription)")
            }
        }
    }
}

**Comment by sbertix** [comment]
You need to move `credentials.code = "121332"` after the authentication handler returns `.failure(let error)`.
Doing it async inside the `if error.requiresInstagramCode { }` might be a good option.

**Comment by rmelnik7777** [comment]
Problem still exists
[https://prnt.sc/pgyf15](url)
apparently does not send this code

**Comment by sbertix** [comment]
Try without the breakpoint. Cause this way you're actually stopping the code as it reaches that row. :blush:

**Comment by rmelnik7777** [comment]
[https://prnt.sc/pgynah](https://prnt.sc/pgynah)
Problem still exists. I would like to draw your attention, I pass the credentials to .user, because if there is .credentials (as in the example), then an error occurs

**Comment by sbertix** [comment]
Where are you getting the `.credentials` case at? 🤔 
It's not even defined… did you implement it yourself? 
Cause otherwise, what's the error you get with `.user`? Cause it feels like that's the actual problem here…

**Comment by sbertix** [comment]
`.user` is the correct way.
`.credentials` was used in `development` and I forgot to change it. Thanks for pointing out. I'll change it right now.
I still don't get the error though cause I'm testing it my way and everything works as intended 🤔

**Comment by sbertix** [comment]
Since I can't see it in your last screenshot. Does it really not work with persisting the `credentials` that way, and then updating `code` after it returns the `Error` requiring it?

**Comment by rmelnik7777** [comment]
If I us .credentials, i have this error [https://prnt.sc/pgyvlx](https://prnt.sc/pgyvlx)
I posted all my code in the main message.
Am I doing something wrong?

**Comment by rmelnik7777** [comment]
how do you test sending a message back?

**Comment by sbertix** [comment]
`.user` is the right one, `.credentials` was kept in the documentation by mistake.
Move your decleration of `credentials` below the `handler` one. As a "retained" property.
It should work then.

**Comment by rmelnik7777** [comment]
its all code, there is an error anyway (


import UIKit
import SwiftyInsta

class ViewController: UIViewController {
    let handler = APIHandler()
    var credentials = Credentials(username: "username", password: "password", verifyBy: .text)
    
    override func viewDidLoad() {
        super.viewDidLoad()
        login()
    }
    
    func login() {
        
        handler.authenticate(with: .user(credentials)) { [weak self] in
            switch $0 {
            case .success(let response, _):
                print("Login successful.")
                guard let key = response.persist() else { return print("`Authentication.Response` could not be persisted.") }
                UserDefaults.standard.set(key, forKey: "current.account")
                UserDefaults.standard.synchronize()
                self?.getCurrentUser()
            case .failure(let error):
                if error.requiresInstagramCode {
                    self!.credentials.code = "178063"
                } else {
                }
            }
        }
    }

    func getCurrentUser() {
        self.handler.users.user(.me) { ( result: Result<User?, Error>) in
            switch result {
            case .success(let user):
                let username = user?.name ?? "John Doe"
                print("success, username: \(username)")
            case .failure(let error):
                print("failure, error: \(error.localizedDescription)")
            }
        }
    }
}

**Comment by sbertix** [comment]
And what is the error this time? @rmelnik7777

**Comment by sbertix** [comment]
That actually looks like some sort of _Xcode_ warning, not something `SwiftyInsta` generated 🤔

**Comment by hassmich** [comment]
I have a similar problem. It is not clear how to get into the failure block to set an authorization code from SMS. Can you help with an example?

**Comment by Yagia** [comment]
Hello I have same problem too. Can you share a working sample application for two factor auth ?

**Comment by TheM4hd1** [comment]
@sbertix will post a clear example soon.
be patient.

**Comment by sbertix** [comment]
Sorry I haven't managed to post an example yet, I've been really busy.
I hope I can post one soon.

**Comment by Lyusan** [comment]
I'm totaly new with swift but maybe I found the bug:

- [Here](https://github.com/TheM4hd1/SwiftyInsta/blob/master/SwiftyInsta/API/Endpoints/AuthenticationHandler.swift#L33-L34), you create a mutable copy of the Credentials and set the value of the handler property.
- But in this line, it's the original Credentials, so the value of handler property is not set. The line is skipped [https://github.com/TheM4hd1/SwiftyInsta/blob/b5d90e3b42696fbcb54211353803bc2e95c0fda0/SwiftyInsta/Local/Authentication/Credentials.swift#L35]

**Comment by sbertix** [comment]
I didn't have a chance to investigate it further but it might be as well be. Apparently on the current commit `Credentials` are declared as a `struct` and not a `class`, which was the premise of the all the passing by reference thing.  
It's apparently something I either fixed along the way in my local version, or some changes that I pushed to the `master` along the way.  
I'll try to review everything in time for #96, but I haven't had any time as of lately. Apologies.
@Lyusan
