### ISSUE TITLE
Unable to get FollowerCount , FollowingCount and TotalPhotosCount directly after Login

### ISSUE THREAD

**Issue by ankitsiliconithub** [TheM4hd1/SwiftyInsta#12]
I see a method 'getUserFollowers' to get followers with detail but please can you help me get  FollowerCount , FollowingCount and TotalPhotosCount directly from Login Call ?!!

**Comment by TheM4hd1** [comment]
You can use ```getUser(id:)``` method after login to receive info and access ```user.followerCount``` , ```user.followingCount``` and ```user.mediaCount``` properties.
Example:
https://github.com/TheM4hd1/SwiftyInsta/blob/a734d8124087a07f5c063f2933a6fe22740beb1f/SwiftyInstaTests/SwiftyInstaTests.swift#L212
