### ISSUE TITLE
Followers I do not follow

### ISSUE THREAD

**Issue by hell4opt** [TheM4hd1/SwiftyInsta#120]
hi, tell me how it’s more logical to implement this:
I want show list of people who follow me but I don’t follow
There can be a lot of followers and sending 1 request per 1 person looks scary, it seems to me if I send it so 1000+ insta requests will be banned
How to be use "/ friendships / show_many /" but there is not complete information about mutual subscription

**Comment by sbertix** [comment]
Easiest way imho: 
1. fetch your followers
1. fetch the ones you follow
1. compare
Cause even `/friendships/show_many/` is not intended to be used with that amount of people.

**Comment by hell4opt** [comment]
> Easiest way imho:
> 
> 1. fetch your followers
> 2. fetch the ones you follow
> 3. compare
> 
> Cause even `/friendships/show_many/` is not intended to be used with that amount of people.

oh my
it's brilliant, thx!
