### ISSUE TITLE
Instagram sends email alert when using random User Agent 

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#123]
It would be better to generate a standard user agent that looks as if the user logged in using Instagram. Is that possible?

**Comment by sbertix** [comment]
Are you setting your own custom user agent?
Cause the ones automatically generated by `SwiftyInsta` never gave me any issue…
@mycroftcanner

**Comment by mycroftcanner** [comment]
Using the ones automatically generated.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/55385694/69068367-8716c580-0a1c-11ea-9165-86f37a106a49.png">

**Comment by sbertix** [comment]
You are using `LoginWebView` or `LoginWebViewController`, correct?
I might try to change it so it matches the `SwiftyInsta` `APIHandler` one, but I would say that you receiving that email is actually "intended behaviour" on Instagram side, and nothing to worry about: you are *indeed* login from a device you don't usually use when dealing with `SwiftyInsta` requests, after all.

**Comment by mycroftcanner** [comment]
ok so this is from the loginwebviewcontroller... and using the handler doesn't generate any warnings... I see.

**Comment by sbertix** [comment]
Yes, cause it's the only place where we simulate being on an iPhone. 
Everywhere else in `SwiftyInsta` you are using a 5 years old Android device hahaha
(We might need to address that too in the future)
