### ISSUE TITLE
Will this API be unavailable in 2020

### ISSUE THREAD

**Issue by raien** [TheM4hd1/SwiftyInsta#124]
To continuously improve Instagram users' privacy and security, we are accelerating the deprecation of Instagram API Platform, making the following changes effective immediately. We understand that this may affect your business or services, and we appreciate your support in keeping our platform secure.

These capabilities will be disabled immediately (previously set for July 31, 2018 or December 11, 2018 deprecation). The following will be deprecated according to the timeline we shared previously:

Public Content - all remaining capabilities to read public media on a user's behalf on December 11, 2018
Basic - to read a user's own profile info and media in early 2020
For your reference, information on the new Instagram Graph API.

**Will this API be unavailable in 2020**

**Comment by TheM4hd1** [comment]
This is for official Instagram API,
this library using unofficial Instagram API. this api extracted from instagram app
