### ISSUE TITLE
Setting scheduler

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#128]
I just noticed my closure are executed on the main thread.

Is there a way to set the default scheduler queue?

**Comment by TheM4hd1** [comment]
you can `.init` the `APIHander` with `.Settings` and set the default queue
`APIHandler(with: .init(delay: ClosedRange<Double>, queues: APIHandler.Settings.Queues, device: Device?, session: URLSession))`

**Comment by mycroftcanner** [comment]
Amazing! thanks
