### ISSUE TITLE
Web view gives error "Get the Instagram App" on login and fails to login

### ISSUE THREAD

**Issue by aliasad106** [TheM4hd1/SwiftyInsta#129]
And even when we press `Not Now` it still fails to get back with the token.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5744468/69570099-e9556480-0fe0-11ea-9bb1-4e838579b104.gif)

**Comment by sbertix** [comment]
What version of `SwiftyInsta` are you on?
@aliasad106

**Comment by sbertix** [comment]
So… it happened to me too 😭 @aliasad106 
I don't know what changed and why it no longer detects the cookies, but I'll try to address it before @TheM4hd1 merges #96 into master.

**Comment by sbertix** [comment]
Ok… so apparently, somewhere in the commit history I removed the "autodetect cookies" feature I implemented. Can't remember why though, tbh. I'll try to see if it still works and add it back.
