### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by TolgaKaramese** [TheM4hd1/SwiftyInsta#13]
Login failed if the password includes special characters like (+,-). But if it is not, works like a charm..

**Comment by TheM4hd1** [comment]
Thanks for reporting this bug, it happens because of encoding request.
I'll fix it.

**Comment by TolgaKaramese** [comment]
And also some usernames return nil while searching it. But i couldn't recognize what causes it.

**Comment by TheM4hd1** [comment]
send me the samples to I can check them.
thanks.

**Comment by TolgaKaramese** [comment]
Pardon me, it caused by me actually 🤦🏻‍♂️ I solved it. And again thank you for your effort to create this project..
