### ISSUE TITLE
avatar arbitrarily picks the first available entry in hdProfilePicVersions

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#130]
avatar arbitrarily picks the first available entry in hdProfilePicVersions

```swift
    public var avatar: URL? {
        return rawResponse.hdProfilePicVersions
            .array?
            .first?
            .url
    }
```

The main issue is that it can be the lowest available quality :

<img width="466" alt="image" src="https://user-images.githubusercontent.com/55385694/69595926-cc2c9000-0ff8-11ea-8651-3959fcd7bb9f.png">

**Comment by mycroftcanner** [comment]
This will select the best available pictures:

```swift

    public var avatar: URL? {
        return rawResponse.hdProfilePicVersions
            .array?.sorted(
        by: {
            guard case .number(let lhs) = $0["width"], case .number(let rhs) = $1["width"] else { return false }
            return lhs.intValue > rhs.intValue
        }
        ).first?["url"]
```

**Comment by sbertix** [comment]
It does, you're right 💪  
I was under the impression avatars were sorted like generic `Media` by size, but apparently they're not.  
Definitely fixing it in #96.
