### ISSUE TITLE
user.avatar will always return nil

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#131]
```
    public var avatar: URL? {
        return rawResponse.hdProfilePicVersions
            .array?
            .first?
            .url
    }
```

`.first?` is a dictionary

**Comment by sbertix** [comment]
Try it 😊 @mycroftcanner  
`.first` is a `DynamicResponse.dictionary` which is marked as `@dynamicMemberLookup`, and its implementation states that `DynamicResponse.dictionary(["key": "value"]).key` equals `"value"`.  
It wouldn't even compile if what you say was true 😊  

([For reference](https://www.avanderlee.com/swift/dynamic-member-lookup/))

**Comment by sbertix** [comment]
I see what you mean.  
There's definitely a `.url` missing there. @mycroftcanner 
Fixing it in #96.
Apologies
