### ISSUE TITLE
is ignoring latestReelMedia and hasBestiesMedia

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#132]
Maybe we could add updatedAt to User

```
updatedAt: Date {
        return rawResponse.latestReelMedia
            .double
            .flatMap { $0 > 9_999_999_999 ? $0/1_000 : $0 }
            .flatMap { Date(timeIntervalSince1970: $0) } ?? .distantPast
    }
```

**Comment by sbertix** [comment]
I cannot recall the reasoning behind not including them in `2.0`. It was probably about focusing on "actual" `User`'s properties, instead of "duplicating" trays.  
That said, I'm open to adding them in #96. 
What do you say? @TheM4hd1

**Comment by mycroftcanner** [comment]
maybe it is better not to add it

**Comment by sbertix** [comment]
💪
