### ISSUE TITLE
'upload(photo:completionHandler:)' is unavailable: Instagram changed this endpoint. We're working on making it work again.

### ISSUE THREAD

**Issue by trentona** [TheM4hd1/SwiftyInsta#139]
Eta? Is this a serious issue? Would it be possible to call the function and ignore instagrams completion handler but compare your uploaded data with the first image on their page and use that as your own completion validation? I just updated my pods and im guessing if it has to do with the completion handler a previous version wouldn't work either, Thanks

**Comment by sbertix** [comment]
Unfortunately it's not about data validation per se.  
It's about _configuring_ the photo, caption and everything, which can only be done after a successful upload and currently does not work properly.  
As soon as we find a workaround we'll update it accordingly.

**Comment by trentona** [comment]
Any update? Is this something that could take awhile? Is there anything I can do to help?

**Comment by TheM4hd1** [comment]
@trentona 
I couldn't still work on it.
if you can try to use this endpoint with `v1` and share the result.
thanks
