### ISSUE TITLE
Search among users 

### ISSUE THREAD

**Issue by TolgaKaramese** [TheM4hd1/SwiftyInsta#14]
Hey Mahdi, 
I wonder about could you add the feature that provides search users. Like search keyword Mahdi returns many of people like instagram search ? 
Thank you..

**Comment by TheM4hd1** [comment]
Feature implemented.
please look at this function as an example and use-case:
https://github.com/TheM4hd1/SwiftyInsta/blob/0b640ba398cce31154c17f049df5f1fecf696e5b/SwiftyInstaTests/SwiftyInstaTests.swift#L191

**Comment by TolgaKaramese** [comment]
I will test it tomorrow but i have no doubt about it works like a charm. Thank you for your quick respond.

**Comment by TolgaKaramese** [comment]
Hey Mahdi, I just recognized that you did not update the features list on
github. People should know about new features that you implemented in I
think :) As reminder ofcourse, It's all up to you.

Mahdi Makhdumi <notifications@github.com>, 10 Nis 2019 Çar, 00:27 tarihinde
şunu yazdı:
