### ISSUE TITLE
Need to sign in again nearly every day

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#141]
I noticed that recently I have to sign in again nearly every day. I am not doing anything out of the ordinary apart from pulling following and checking stories in the tray.

**Comment by TheM4hd1** [comment]
Instagram forcing users to re-login if detects an unusual activity.
Also request limit changed again, so if you're using the user as a middle-way to check stories for other users, this can affect this issue too.
