### ISSUE TITLE
Conflicts with parse library.

### ISSUE THREAD

**Issue by developweb10** [TheM4hd1/SwiftyInsta#143]
Hi,
First of all, thank you for providing us a cool library, here is the issue I am facing when I am adding this pods , parse pod library is creates conflicts. The conflicts are as follow:
-> Duplicate interface definition for class 'Parse'.
-> Property has a previous declaration.

Please note My existing project is in objective c.

**Comment by sbertix** [comment]
Hey @developweb10 
There's no `Parse` class in `SwiftyInsta` or its dependencies.
Are you sure it's not something else causing the conflict? 🤔
