### ISSUE TITLE
Caching Problem

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#145]
When I am requesting for followers/following or media likers api returns wrong users which I do know them. How it is possible? (it happens some of my friend account not all)

**Comment by TheM4hd1** [comment]
provide more information
attach the returned data, what you request, what you expect. so we can analyze it

**Comment by flamme0011** [comment]
I am using old version of this lib. (Version -> 1.7.5)

Using Method:

try self.handler.getMediaLikers(mediaId: media.id!, completion: { (result) in
           //Get users in here
})

In my friend phone it returns wrong users but when I tried it in myphone with same instagram user it returns correct.

It always happens in different user and different phones. But some of different users it is working correctly.

**Comment by TheM4hd1** [comment]
are those accounts able to see media likers on official app?
because some of accounts are limited to see media liker.

**Comment by flamme0011** [comment]
yes we can see media likers on official app and the main problem is caching I think because same account different phones one of them show correct data and other one is wrong

**Comment by sbertix** [comment]
Please update to `2.*`.  
Multi account and complete cookie flashing were not implemented back then.
