### ISSUE TITLE
Smart  endpoints

### ISSUE THREAD

**Issue by hell4opt** [TheM4hd1/SwiftyInsta#146]
in SwiftyInsta provides endpoints to confuse insta) for example endpoints of scrolling a tap when parsing followers I attach off messages from insta - https://imgur.com/8kWMuF4

**Comment by sbertix** [comment]
Unfortunately I'm not aware of the actual endpoints to do, so there's not much I can do right now, and I feel like @TheM4hd1 would have added them if he knew them.  
Do you have any idea of what the actual endpoints are? In that case feel free to reopen this issue, or send a pull request.
😊

**Comment by hell4opt** [comment]
> Unfortunately I'm not aware of the actual endpoints, so there's not much I can do right now, and I feel like @TheM4hd1 would have added them if he had known them.
> Do you have any idea of what the actual endpoints are? In that case feel free to reopen this issue, or send a pull request.

if I find these points, I will write to you)
