### ISSUE TITLE
Story Viewers

### ISSUE THREAD

**Issue by TolgaKaramese** [TheM4hd1/SwiftyInsta#15]
Can we add the feature provides that reaching logged in user's stories' viewer list ?

**Comment by TheM4hd1** [comment]
I'm not sure if I get it.
You want a list of users who visited your story?
Describe more please.

**Comment by TolgaKaramese** [comment]
Exactly

**Comment by TheM4hd1** [comment]
okay, I'll work on it tomorrow

**Comment by TolgaKaramese** [comment]
Thank you, also you can label the issue as feature

**Comment by TheM4hd1** [comment]
Feature added and works fine, test it and let me know if anything went wrong.
usage example: 
https://github.com/TheM4hd1/SwiftyInsta/blob/6847538b9287db51e8d79e36737146bf51764591/SwiftyInstaTests/SwiftyInstaTests.swift#L1268

Also there is another way to count ```StoryViewers```, you can use ```getStoryFeed``` function to receive the complete feed of stories which includes own user stories too.

in this case to find out who visited your story you can use the function result like this:

```swift
let userStories = result.value!.tray!.first(where: { (tray) -> Bool in
    tray.user!.username! == HandlerSettings.shared.request!.username
})
print(userStories!.items!.compactMap {$0.viewers!})
```

NOTE: currently the implemented function doesn't returns all viewers (returns a limited number), I don't had enough users to visit my stories so I will push another update in future to complete this function.

**Comment by TolgaKaramese** [comment]
Hey Mahdi,
Did you apply new features to pods ? If you don't could you please add them
? If you do there is a problem with it :D Anyway is there any quicker
contact method with you such as skype, facebook etc ?

Mahdi Makhdumi <notifications@github.com>, 16 Nis 2019 Sal, 01:51 tarihinde
şunu yazdı:

**Comment by TheM4hd1** [comment]
@TolgaKaramese yeah it added to pod
what’s the problem?
skype: live:mahdimakhdomi
