### ISSUE TITLE
Is it possible to find Users' location ?

### ISSUE THREAD

**Issue by aliasad106** [TheM4hd1/SwiftyInsta#150]
I'm trying to track the locations of followings and followers.

**Comment by sbertix** [comment]
Sorry for the late reply.  
It is not, it's not data returned by any available endpoint, and frankly data I'm not even sure Instagram collects as such.  

If you refer to the **Threads** app feature instead, I'm not currently aware of the related endpoints, so still no way to help, I'm afraid.
