### ISSUE TITLE
Off top question. What do you use as source?

### ISSUE THREAD

**Issue by Leadro** [TheM4hd1/SwiftyInsta#151]
Hi there,

as you maybe know mgp25's repo of Private API was [banned (https://twitter.com/_mgp25/status/1222715332013502464)

And from here is my question. What do you use as source for building library?
mgp25 repo? or you making own reverse engineering process and build your library from it?

WBR
Leadro

**Comment by TheM4hd1** [comment]
Hello,
The library mainly used the mgp25 library, it was a port of php version at the beginning.
but there are a few features that we added for first time (mix of web api and native api), but at the end, Yes, we were using the mgp25 library.

**Comment by Leadro** [comment]
In this case we have lost the main source of new endpoints, logic updates and other stuff ((

**Comment by Leadro** [comment]
maybe some one of contributors has an access to Premium licence ;)
