### ISSUE TITLE
Reels media items is empty

### ISSUE THREAD

**Issue by bariscck** [TheM4hd1/SwiftyInsta#152]
Im trying to get reels media of some users, rawResponse is fine but items (TrayElements) returns empty array and I couldn't access media.

```
handler.stories.reelsMedia(userIds, completionHandler: { (response) in
    switch response {
    case .success(let dict):
        dict.values.forEach { (tray) in
            print(tray.items.map { $0 }) // -> This returns empty array []
            print(tray.rawResponse.items.array?.map { $0 }) // -> This is fine
        }
    case .failure(let error):
            print(error.localizedDescription)
     }
})
```

**Comment by sbertix** [comment]
Apparently `tray.items` actually accesses `tray.rawResponse.tray.array` instead of `.items`.  
It might have either changed or it was based on another response, but I'm definitely fixing this soon.  
Thx 😊

**Comment by anonrig** [comment]
Any update on this?

**Comment by bariscck** [comment]
@sbertix thanks for quick response and the fix 😊I can access `tray.items`, but item's media objects is empty now.

**Comment by sbertix** [comment]
That's intended, if I understand correctly.  
`TrayElement` are not always immediately populate. You need to call the appropriate method with the related identifier.

**Comment by bariscck** [comment]
@sbertix `rawResponse` is fine I can see all urls in `rawResponse`, and model is fine excluding `media`.

```
handler.stories.reelsMedia(userIds, completionHandler: { (response) in
    switch response {
    case .success(let dict):
        dict.values.forEach { (tray) in
            print(tray.rawResponse.beautifiedDescription) // -> This is fine I can see all Url's
            print(tray.items.first?.user) // -> This is fine, I can reach User object
            print(tray.items.first?.media) // -> This returns empty array []
        }
    case .failure(let error):
            print(error.localizedDescription)
     }
})
```

**Comment by sbertix** [comment]
I've realised where the issue is 😞. 
`reelsMedia` was never supposed to "return" `[String: Tray]`, but always `[String: TrayElement]`. That's why properties aren't matching. I'm pushing a PR asap.
