### ISSUE TITLE
Setting user agent on loginview

### ISSUE THREAD

**Issue by anonrig** [TheM4hd1/SwiftyInsta#155]
Is seems that there isn't any possibility to change the user agent of login web view. Today my application got rejected due to the webview having a "Find it for free on Google Play" header on Instagram login page, due to Android user-agent of the wkwebview.

**Comment by sbertix** [comment]
Definitely something we could implement.  
Feel free to push a PR, if it's urgent, cause I'm not sure when I can get down to it 😊

Still, please keep in mind that `WKWebView` based authentication, like `LoginWebView` is, requiring full access to a third party user account through cookies is usually not allowed in the App Store, and might be caused for rejection, Android banner or not.

**Comment by sbertix** [comment]
I've added support for this in #156.  
It'll be merged to `master` as soon as @TheM4hd1 reviews it 😊💪
