### ISSUE TITLE
`reelsMedia` should return `[String: TrayElement]`

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#159]
I've realised where the issue is 😞. 
`reelsMedia` was never supposed to "return" `[String: Tray]`, but always `[String: TrayElement]`. That's why properties aren't matching. I'm pushing a PR asap.

_Originally posted by @sbertix in https://github.com/TheM4hd1/SwiftyInsta/issues/152#issuecomment-593901982_

**Comment by sbertix** [comment]
Done @bariscck 😊 
PR sent.

**Comment by bariscck** [comment]
@sbertix thanks for the fix, it works fine 😊
