### ISSUE TITLE
Getuser throws EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

### ISSUE THREAD

**Issue by podycust** [TheM4hd1/SwiftyInsta#16]
when trying to get user info Xcode 10 just throws an EXC_BAD_ACCESS (code=EXC_I386_GPFLT) error even when using the get user from tests

**Comment by TolgaKaramese** [comment]
Could you share your steps ?

**Comment by TheM4hd1** [comment]
[-] Describe steps
[-] Function name
[-] Attach your code
[-] Attach screenshot

**Comment by podycust** [comment]
once I log user in I try to get info about the signed in user using handler.getuser()

![Screenshot 2019-04-16 at 11 01 59](https://user-images.githubusercontent.com/362102/56200753-4ba3bb00-6037-11e9-8f17-a2dd49f2e31f.png)
![Screenshot 2019-04-16 at 11 00 44](https://user-images.githubusercontent.com/362102/56200756-4cd4e800-6037-11e9-96b5-2a377d21edf9.png)

**Comment by TheM4hd1** [comment]
As it appears from your console, the username value could not be read.
Please check the username you entered.
If you need more help, send me your Skype to check it remotley.
