### ISSUE TITLE
PaginationParameters is not working

### ISSUE THREAD

**Issue by bariscck** [TheM4hd1/SwiftyInsta#164]
I am trying to fetch user's medias with `PaginationParameter`. 

If I set `maxPageLoads` to 1, only fetching first page and `nextMaxId` returns `nil`. 
If I set `maxPageLoads` to 2, fetching 2 pages on first request and returns `nextMaxId` but after that not fetching any data with this `nextMaxId`.

**Comment by sbertix** [comment]
Yes. Definitely a bug (`PaginationHelper.swift:153`).  
It actually returns the currently requested one on complete, instead of the next one.  
I'm pushing a fix asap. @bariscck

**Comment by sbertix** [comment]
I'll wait for the quick fix to the other PR and then push a new patch version. 💪

**Comment by bariscck** [comment]
@sbertix thanks for the quick fix but this not fix this issue. I've tried your fixed code but nothing changes, still issue continues.

**Comment by sbertix** [comment]
Are you accessing it for the `updateHandler` or the `completionHandler`.  
Cause I haven't changed it for `updateHandler`, only `completionHandler`, although, tbh, `nextMaxId` should indeed mean "the next one" either way, and I'm pretty sure it wouldn't cause troubles to anyone.  
I'm force pushing another try if you don't mind testing it again 😊 @bariscck

**Comment by sbertix** [comment]
And I'm actually changing the `PaginationParameters` so it keeps both the "current" and "next" `max_id`.

**Comment by sbertix** [comment]
Forced push another try to `sb/bugfixes`.  
I've added `currentMaxId` to `PaginationParameters` too, just to avoid confusion in use cases.  
Let me know if it works this way 😊 @bariscck

**Comment by bariscck** [comment]
I'm accessing `completionHandler` like this;

```
private var userFeedPagination: PaginationParameters?

private func fetchUserFeed(for pk: Int) {
        var nextMaxId: String?
        
        if let userFeedPagination = userFeedPagination {
            nextMaxId = userFeedPagination.nextMaxId
        }
        
        let paginationParams = PaginationParameters(startingAt: nextMaxId)
        dependency.handler.media.by(user: .primaryKey(pk), with: paginationParams, updateHandler: nil) {
            [weak self] (result, pagination) in
            
            switch result {
            case .success(let medias):

                print(pagination.nextMaxId)
                print(pagination.canLoadMore)

                self?.userFeedPagination = pagination

            case .failure(let error):
                print(error.localizedDescription)
            }
        }
    }
```

Anything wrong with this code?

**Comment by sbertix** [comment]
Nope. Looks absolutely fine to me 😊  
Let me know if the new version actually works 🤞

**Comment by bariscck** [comment]
It works like a charm! Thanks 😊But I think `canLoadMore` is also broken because always returns `false`.

**Comment by sbertix** [comment]
Thanks for pointing it out cause I totally forgot to change it too, according to the new edits 💪 
I'm gonna fix it and merge it in the next couple of hours.

**Comment by sbertix** [comment]
Yeah `canLoadMore` is one of the relics from `1.*`, that I didn't try to change too much.  
It only holds whether you have reached the maximum amount of pages you set in the request.  
No use for it to be `public` tbh.  
I'm definitely deprecating that too.
