### ISSUE TITLE
Login Advertisement

### ISSUE THREAD

**Issue by arda0011** [TheM4hd1/SwiftyInsta#166]
Is there a any way to remove advertisement in login page?

You can see in the image and there is an advertisement top of the view like find it free on google play

https://imgur.com/a/a6GANd8

**Comment by sbertix** [comment]
Hey @arda0011 😊  
This gets asked pretty often, as you might imagine, and you can find previous reference both on Issues and Pull Requests.  
Unfortunately it doesn't seem the case, cause it looks like Instagram has a way to check for the integrity of the requesting web page, resulting in a blank page with no cookies in case it's been tempered with.

tl;dr: unfortunately not.
