### ISSUE TITLE
IOS 11 Login

### ISSUE THREAD

**Issue by MariaJsn** [TheM4hd1/SwiftyInsta#168]
Hi
I could not open login screen with ios 11 device on my simulator. In ios 13 it is working correctly.  How can I open login screen in ios 11?

Login screen on ios 11 device like: https://ibb.co/6N9x0Kc

Please can you help me?
Thanks,
Maria

My code:

    let login = LoginWebViewController { controller, result in
    controller.dismiss(animated: true, completion: nil)
    // deal with authentication response.
    guard let (response, _) = try? result.get() else { return print("Login failed.") }
    print("Login successful.")
    // persist cache safely in the keychain for logging in again in the future.
    guard let key = response.persist() else { return print("`Authentication.Response` could not be persisted.") }
    // store the `key` wherever you want, so you can access the `Authentication.Response` later.
    // `UserDefaults` is just an example.
    UserDefaults.standard.set(key, forKey: "current.account")
    UserDefaults.standard.synchronize()
}

    override func viewDidLoad() {
        super.viewDidLoad()
   
            if #available(iOS 13, *) {
                present(login, animated: true, completion: nil) 
            } else {
                present(UINavigationController(rootViewController: login),  
                        animated: true,
                        completion: nil)
            }
      
    }

**Comment by sbertix** [comment]
Interesting… 🤔 
I genuinely can't see the issue, tbh. There's no difference in `LoginView` and `LoginViewController` for the two versions.
Are you using the last version?
I feel like it might not be an issue with **SwiftyInsta**, but something else, though.

**Comment by MariaJsn** [comment]
yes I am using the latest version. Is it because of the simulator? I could not find real device which has ios 11. And if it is possible for you can you try in your simulator which has ios 11 please

**Comment by sbertix** [comment]
I'm downloading the iOS 11.0 Simulator to test it.  
Full disclosure though: if it doesn't work, since it's not a bug with **SwiftyInsta** code, there's nothing I can do to fix it, so I'll just bump the availability for `LoginView` to iOS 12.

**Comment by MariaJsn** [comment]
thanks for all your help and waiting your simulator results

**Comment by sbertix** [comment]
Indeed the webpage never moves beyond the "Instagram logo" phase, so I assume the problem is with Instagram maybe restricting access to older devices.  
I'll test it for iOS 12 and push a PR with a new `@available` lower version, accordingly.
Thanks for pointing this out 😊

**Comment by MariaJsn** [comment]
so after your PR ios 11 will work or will work only ios 12? You will try to solve the issue for ios 11?

**Comment by sbertix** [comment]
Only iOS 12. It's not an issue with **SwiftyInsta**, but either with iOS 11 or Instagram restricting access to older devices. So there's no way for me to fix it.  
`LoginWebView` and `LoginWebViewController` will be iOS 12 and above only, as referenced in #169.
