### ISSUE TITLE
Story Tray returns missing data

### ISSUE THREAD

**Issue by MariaJsn** [TheM4hd1/SwiftyInsta#175]
When I request to story tray I can get only first user stories, other story items not returning from api.

I am using:  
handler.stories.tray(completionHandler: {(response) in
        
           switch response {
            case .success(let stories):
                let storyData = stories.rawResponse
                print(storyData.beautifiedDescription)

Result:

{
  "broadcasts" : [

  ],
  "faceFilterNuxVersion" : 7,
  "hasNewNuxStory" : false,
  "refreshWindowMs" : 0,
  "status" : "ok",
  "stickerVersion" : 5,
  "storiesViewerGesturesNuxEligible" : true,
  "storyRankingToken" : "580dcc06-64ad-484c-9427-ba53f7cb0add",
  "tray" : [
    {
      "canGifQuickReply" : true,
      "canReply" : true,
      "canReshare" : true,
      "expiringAt" : 1586785338,
      "hasBestiesMedia" : false,
      "id" : 325734299,
      "items" : [
        {
          "canReply" : true,
          "canReshare" : true,
          "canSeeInsightsAsBrand" : false,
          "canSendCustomEmojis" : false,
          "canViewerSave" : true,
          "caption" : null,
          "captionIsEdited" : false,
          "captionPosition" : 0,
          "clientCacheKey" : "MjI4NTcwMzA4MzM0MjY0NjI4OA==.2",
          "code" : "B-4ctgYp0wQ",
          "deviceTimestamp" : 1586697061511111,
          "expiringAt" : 1586783461,
          "filterType" : 0,
          "id" : "2285703083342646288_325734299",
          "imageVersions2" : {
            "candidates" : [
              {
                "estimatedScansSizes" : [
                  19127,
                  38254,
                  57382,
                  76509,
                  95637,
                  107017,
                  136184,
                  154780,
                  172147
                ],
                "height" : 2000,
                "url" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.12442-15\/e35\/92984056_811523482674555_302576339883237026_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=OZyiQEQMcIQAX-_AD1x&se=7&oh=f8c9a8cc5f8fc28b08d644f968cd4583&oe=5E956C58&ig_cache_key=MjI4NTcwMzA4MzM0MjY0NjI4OA%3D%3D.2",
                "width" : 1125
              },
              {
                "estimatedScansSizes" : [
                  6119,
                  12239,
                  18359,
                  24479,
                  30598,
                  36839,
                  1063125,
                  55078,
                  55078
                ],
                "height" : 853,
                "url" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.12442-15\/e35\/p480x480\/92984056_811523482674555_302576339883237026_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_cat=1&_nc_ohc=OZyiQEQMcIQAX-_AD1x&oh=6b64d0067e8a9fabcac019ea08f8d4fa&oe=5E952484&ig_cache_key=MjI4NTcwMzA4MzM0MjY0NjI4OA%3D%3D.2",
                "width" : 480
              }
            ]
          },
          "isReelMedia" : true,
          "mediaType" : 1,
          "organicTrackingToken" : "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZmU2ZDYxZGY3OTMzNGY4Y2IzNjI1Yzg2MTM3NDgzYjQyMjg1NzAzMDgzMzQyNjQ2Mjg4Iiwic2VydmVyX3Rva2VuIjoiMTU4NjcwMDg0NDA0NXwyMjg1NzAzMDgzMzQyNjQ2Mjg4fDEyNjExNzE0NDExfDdjYmY4OTQxYjI5OGE0NWNlYWU2NzBhODgyMDEyMjE5MGZmMzBhYTk1NmM5MTAwYTk4OTM4OWIyZjZhN2Y4ODgifSwic2lnbmF0dXJlIjoiIn0=",
          "originalHeight" : 2000,
          "originalWidth" : 1125,
          "photoOfYou" : false,
          "pk" : 2285703083342646288,
          "reelMentions" : [
            {
              "displayType" : "mention_reshare",
              "height" : 0.5,
              "isFbSticker" : 0,
              "isHidden" : 0,
              "isPinned" : 0,
              "isSticker" : 0,
              "rotation" : 0,
              "user" : {
                "fullName" : "V Magazine",
                "isPrivate" : false,
                "isVerified" : true,
                "pk" : 22636146,
                "profilePicId" : "2238808188841707274_22636146",
                "profilePicUrl" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.2885-19\/s150x150\/83103498_184867302734815_7813499144487567360_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_ohc=-AWC_FmLyP4AX_Xv6XJ&oh=fa37df3ca858162aff59e420afa504c5&oe=5EBBE7D5",
                "username" : "vmagazine"
              },
              "width" : 0.5,
              "x" : 0.5,
              "y" : 0.5,
              "z" : 0
            }
          ],
          "showOneTapFbShareTooltip" : true,
          "supportsReelReactions" : true,
          "takenAt" : 1586697061,
          "user" : {
            "isPrivate" : false,
            "pk" : 325734299
          }
        },
        {
          "canReply" : true,
          "canReshare" : true,
          "canSeeInsightsAsBrand" : false,
          "canSendCustomEmojis" : false,
          "canViewerSave" : true,
          "caption" : null,
          "captionIsEdited" : false,
          "captionPosition" : 0,
          "clientCacheKey" : "MjI4NTcxODgzOTE1MzI1MjQwOA==.2",
          "code" : "B-4gSyIJdg4",
          "deviceTimestamp" : 1586698939357791,
          "expiringAt" : 1586785338,
          "filterType" : 810,
          "id" : "2285718839153252408_325734299",
          "imageVersions2" : {
            "candidates" : [
              {
                "estimatedScansSizes" : [
                  20978,
                  41956,
                  62935,
                  83913,
                  104892,
                  117374,
                  149362,
                  169758,
                  188806
                ],
                "height" : 2000,
                "url" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.12442-15\/e35\/92395930_638765060020289_4215649224880495177_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=Kg-i1YghRd8AX8txChJ&se=7&oh=859c6ec9bdb5cbe24f844684b7c4cdb5&oe=5E959B08&ig_cache_key=MjI4NTcxODgzOTE1MzI1MjQwOA%3D%3D.2",
                "width" : 1125
              },
              {
                "estimatedScansSizes" : [
                  6360,
                  12720,
                  19080,
                  25440,
                  31801,
                  38286,
                  1104878,
                  57242,
                  57242
                ],
                "height" : 853,
                "url" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.12442-15\/e35\/p480x480\/92395930_638765060020289_4215649224880495177_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=Kg-i1YghRd8AX8txChJ&oh=01fd4e704a790486b0eece42cd5f1ef2&oe=5E95BC00&ig_cache_key=MjI4NTcxODgzOTE1MzI1MjQwOA%3D%3D.2",
                "width" : 480
              }
            ]
          },
          "importedTakenAt" : 1586698844,
          "isReelMedia" : true,
          "mediaType" : 1,
          "organicTrackingToken" : "eyJ2ZXJzaW9uIjo1LCJwYXlsb2FkIjp7ImlzX2FuYWx5dGljc190cmFja2VkIjp0cnVlLCJ1dWlkIjoiZmU2ZDYxZGY3OTMzNGY4Y2IzNjI1Yzg2MTM3NDgzYjQyMjg1NzE4ODM5MTUzMjUyNDA4Iiwic2VydmVyX3Rva2VuIjoiMTU4NjcwMDg0NDA0NHwyMjg1NzE4ODM5MTUzMjUyNDA4fDEyNjExNzE0NDExfDE0Y2Q1MzljZjBkNTMyZWE2ZDk2NDM4N2YyN2VhMGRiMGM4ZGE1NTI3MDY3NGNlMTNmNTQzNGVjYzI0MjUxYzEifSwic2lnbmF0dXJlIjoiIn0=",
          "originalHeight" : 2000,
          "originalWidth" : 1125,
          "photoOfYou" : false,
          "pk" : 2285718839153252408,
          "showOneTapFbShareTooltip" : true,
          "supportsReelReactions" : true,
          "takenAt" : 1586698938,
          "user" : {
            "isPrivate" : false,
            "pk" : 325734299
          }
        }
      ],
      "latestBestiesReelMedia" : 0,
      "latestReelMedia" : 1586698938,
      "mediaCount" : 2,
      "muted" : false,
      "prefetchCount" : 1,
      "rankedPosition" : 1,
      "reelType" : "user_reel",
      "seen" : 0,
      "seenRankedPosition" : 1,
      "user" : {
        "friendshipStatus" : {
          "following" : true,
          "isMutingReel" : false,
          "muting" : false,
          "outgoingRequest" : false
        },
        "fullName" : "Miley Cyrus",
        "isPrivate" : false,
        "isVerified" : true,
        "pk" : 325734299,
        "profilePicId" : "2270780004489262281_325734299",
        "profilePicUrl" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.2885-19\/s150x150\/90305325_155405542324771_3638194490667171840_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_ohc=vsIe8Pc_Ks0AX_DugWk&oh=6b8297965ffe5efd5bba1bf7bcef4fb7&oe=5EBE7100",
        "username" : "mileycyrus"
      }
    },
    {
      "canGifQuickReply" : true,
      "canReply" : true,
      "canReshare" : true,
      "expiringAt" : 1586744105,
      "hasBestiesMedia" : false,
      "id" : 18428658,
      "latestBestiesReelMedia" : 0,
      "latestReelMedia" : 1586657705,
      "mediaCount" : 15,
      "muted" : false,
      "prefetchCount" : 0,
      "rankedPosition" : 2,
      "reelType" : "user_reel",
      "seen" : 1586657705,
      "seenRankedPosition" : 2,
      "user" : {
        "friendshipStatus" : {
          "following" : true,
          "isMutingReel" : false,
          "muting" : false,
          "outgoingRequest" : false
        },
        "fullName" : "Kim Kardashian West",
        "isPrivate" : false,
        "isVerified" : true,
        "pk" : 18428658,
        "profilePicId" : "2216903602755081982_18428658",
        "profilePicUrl" : "https:\/\/instagram.fsaw3-1.fna.fbcdn.net\/v\/t51.2885-19\/s150x150\/79825544_470124460599150_1224692418167701504_n.jpg?_nc_ht=instagram.fsaw3-1.fna.fbcdn.net&_nc_ohc=mMnnYhExFt4AX-CH8u9&oh=706013fa327cb67d943162b25b154435&oe=5EBC746C",
        "username" : "kimkardashian"
      }
    }
  ]
}

**Comment by sbertix** [comment]
Again. It's working as intended and it depends on that endpoint itself.  
Only the first object is populated, for the next one you need to pass the user identifier to the user-specific identifier 😊
