### ISSUE TITLE
Invalid response error. (429)

### ISSUE THREAD

**Issue by anilsari** [TheM4hd1/SwiftyInsta#176]
when i try to get mediaLike and mediaComment ,I get this error after 3-4 requests 
Invalid response.\n{\n  \"message\" : \"Please wait a few minutes before you try again.\",\n  \"status\" : \"fail\"\n}.\n429"

:/

**Comment by sbertix** [comment]
Exactly as it says 😊 
It means you've reached the limit of allowed requests to that specific endpoint and you need to wait a while.  
Nothing to do with **SwiftyInsta** per se, just Instagram anti-spam filter.
