### ISSUE TITLE
KeychainSwift defaults to accessibleWhenUnlocked

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#179]
The following code has been driving me crazy for the past two weeks :

```swift
      isEnabledAndHasKeychainPublisher
            .sink { isEnabled, keychainKey in
                guard isEnabled && !keychainKey.isEmpty else {
                    os_log("Missing keychain key", log: .ig, type: .debug)
                    return
                }

                guard let cache = Authentication.Response.persisted(with: keychainKey) else {
                    DispatchQueue.main.async {
                        os_log(
                            "`Authentication.Response` not found [%s].",
                            log: .ig,
                            type: .debug,
                            keychainKey
                        )
                        self.instagramKeychainKey = ""
                    }
                    self.cacheSubject.value = nil
                    return
                }
                self.cacheSubject.value = cache
            }
            .store(in: &cancellables)
```

The above code would work perfectly in the simulator.... On my development phone it would work but when I would open the app the next day, the keychain data would go missing for no reason. 

I looked through my code and the only place the keychain data would be invalidated is in my signout method... Nothing in SwiftyInsta raised a bell...  

Apparently the problem is that KeychainSwift defaults to `accessibleWhenUnlocked` instead of `accessibleAfterFirstUnlock`. 

```swift
  static var defaultOption: KeychainSwiftAccessOptions {
    return .accessibleWhenUnlocked
  }
```

**Comment by sbertix** [comment]
Yep, `kSecAttrAccessibleWhenUnlocked` is indeed the default access option for the **Security** framework, as its porting `accessibleWhenUnlocked` is for **KeychainSwift**.  
I'm assuming the code is supposed to be running in the background, right, or it would make no difference.   

Unfortunately **SwiftyInsta** hasn't been written with cookie caching support in mind from the beginning, and when I added it, I just botched it. It works: no configs, no fuss, no nothing. "It just works" hahahaha
I really don't think editing existing code to add custom keychain access options or storage types makes much sense: it's already hard enough to maintain as is.  

(I know it's not "nice" to say, but as a way to overcome some of the "challenges" with **SwiftyInsta** I've started working on a new project. It allows for custom cookie caching and access options for a Keychain-based storage is being added as we speak. [Just in case](https://github.com/sbertix/Swiftagram))

**Comment by mycroftcanner** [comment]
why not have a configuration option for KeychainSwift??  It took me 30 seconds to fix and now I would have to maintain a fork just for that?? I can send you a PR if you prefer.

**Comment by mycroftcanner** [comment]
I'll port my app to use Swiftagram. Do you have a link to a roadmap and current status? Happy to help with the code as well.

**Comment by sbertix** [comment]
> why not have a configuration option for KeychainSwift?? It took me 30 seconds to fix and now I would have to maintain a fork just for that?? I can send you a PR if you prefer.

It's not about "complexity" on adding it. It's just about "cost effectiveness", but for me: it doesn't have to be for you, for instance. So if you want to push a PR adding it to **SwiftyInsta** you're more than welcome: I'll be happy to merge it myself 😊 

> I'll port my app to use Swiftagram. Do you have a link to a roadmap and current status? Happy to help with the code as well.

You can find something on the Projects board and visiting the Wiki and the docs.  
I'm mostly focusing on closing the endpoint gap and updating to **ComposableRequest** 3.0 (so do not migrate just now: wait for `2.0.0`, being worked on `development` as we speak).  
Any contribution is more than welcome 😊

**Comment by mycroftcanner** [comment]
Here is a workaround using an extension if someone has the same issue:

```swift
extension Authentication.Response {
    public func persistAndAccessibleAfterFirstUnlock() -> String? {
        guard let id = user?.id else { return nil }

        let encoder = JSONEncoder()
        let keychain = KeychainSwift()
        let key = String(id)

        guard let data = try? encoder.encode(self) else { return nil }
        keychain.set(data, forKey: key, withAccess: .accessibleAfterFirstUnlock)
        return key
    }
}
```
