### ISSUE TITLE
weakObject handler.users.user

### ISSUE THREAD

**Issue by zkquin** [TheM4hd1/SwiftyInsta#180]
Hi TheM4hd1 and team, lovely API you've put together. Thank you. 

I'm having an issue when making the following request. If I replace the primary key with '.me' or '.username(String)' the request works. 

`handler.users.user(.primaryKey(Int), completionHandler: { (res) in`

The authed user has permission to view the profile, as when this request is made using their username it works as it should.

Any help would be appreciated.

**Comment by sbertix** [comment]
Hey 💪 
It's not really clear but I'm assuming, from the title, you are receiving a `GenericError.weakObjectReleased` error, right?  
All you need to is strongly reference your `handler` instance somewhere in your code.

e.g.
```swift
class MyModel {
     var handler: APIHandler = APIHandler()
     
     // authenticate `handler` somewhere.
     // call the endpoints.
     func user(for primaryKey: Int) {
          handler.users.user(.primaryKey(primaryKey)) { _ in }
     } 
}
```

**Comment by zkquin** [comment]
Ah thank you kindly, this worked, rookie mistake.

**Comment by sbertix** [comment]
Np. Glad I could help 💪
