### ISSUE TITLE
Instagram Ajax Login 

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#184]
Did Instagram just nuke `instagram.com/accounts/login/ajax`, or is it just me?  
I can't seem to make it work.
😱

Do you mind testing the basic auth process?
Cause unfortunately an alternative one would require way too many dependencies in Swift (as it uses both hashes and RSA).

@TheM4hd1 @bariscck

---
Edit: not working in **Swiftagram** either… 😱 did they really just get rid of it?

**Comment by TheM4hd1** [comment]
it worked for me, however couldn't get the challenge code from sms, but it worked with email.

**Comment by bariscck** [comment]
`Swiftagram`'s `BasicAuthenticator.handleSecond` returns `invalid response`

**Comment by sbertix** [comment]
I can't make it work on SwiftyInsta either 😢  @bariscck 
I can't even make it work from Insomnia and Postman… 😱 
I hope it's just some temporary issue at Instagram…

**Comment by bariscck** [comment]
It seems temporary, because Instagram's web app using this endpoint currently. It doesn't work for them either. Returns `400` `Bad Request`.

**Comment by TheM4hd1** [comment]
the web app works for me too, however I remember about 4 month ago same thing happened and fixed after a few hours.

**Comment by sbertix** [comment]
Yep, it did happened before but we used to get `400` back, which is reasonable.  
Direct access gets `405` this time.  
I'm scared they might just be migrating away from it.

**Comment by Emretelli7** [comment]
hello, i am getting same problem too, is that solved for you?

**Comment by sbertix** [comment]
Still unsolved, unfortunately @Emretelli7. 
I feel like we need to accept the endpoint is just gone 😢

**Comment by xmmti** [comment]
Hi, now instagram use **"enc_password"** you can't use **"password"** 
![image](https://user-images.githubusercontent.com/50987834/82104548-095c1a00-9720-11ea-89b6-f3bdf810e968.png)
enc_password use AES 256 GCM encryption

https://pastebin.com/raw/nYL2W2bG

**Comment by Emretelli7** [comment]
@xmmti 
i tried copy my enc_password from burp suite and post it with my username but turned authenticated: false

so it means i think there is something more than this enc_password

**Comment by xmmti** [comment]
> @xmmti
> i tried copy my enc_password from burp suite and post it with my username but turned authenticated: false
> 
> so it means i think there is something more than this enc_password

Body Request 
username=*Your Username*&enc_password=*enc_password*
![image](https://user-images.githubusercontent.com/50987834/82105037-fa766700-9721-11ea-987d-8dbdfbdd9fc8.png)
I it's work with me...

**Comment by sbertix** [comment]
Yep. It's way more than just that. I hint at that on my first note.  
The new headless authentication method requires cryptography tools that are definitely not standard in Swift. Hashes are quite easy to come by (and they're already in **SwiftyInsta** through CryptoSwift) but I couldn't find a reliable RSA library in the past (def not for non current releases), and it would be (at least) one more dependency.

**Comment by xmmti** [comment]
*API* login work fine with me... just ajax his enc_password

**Comment by sbertix** [comment]
Please read my comment @xmmti. 

We're all totally aware of a fix. We were before even writing the issue, and we know this was gonna happen sooner or later.  
Thing is the fix is super easy for Node JS, or in Python, but definitely not in Swift cause there are no good library for cryptography and **CryptoSwift**, currently required by **SwiftyInsta**, or anything based out of **CommonCrypto** for that matter, is simply not extensive enough.

**Comment by Emretelli7** [comment]
@sbertix 
hello i am here for my python project because i was getting same problem. 
If you want to use it on your mobile app you can run a server which is running python script to connect with your mobile app.

**Comment by sbertix** [comment]
This is not an issue for me @Emretelli7, but thanks. 😊  
I already have my authentication routed through a node app.  
This is about providing basic authentication directly in **SwiftyInsta**.

**Comment by bariscck** [comment]
Basic login seems to be working now, I checked two different accounts with and without `2FA`.

**Comment by MatoMA** [comment]
We'll try to use swift-sodium, a wrapper for libsodium. Hope it works.

**Comment by sbertix** [comment]
Be careful in adding too many dependencies @MatoMA and keep in mind SwiftyRSA does not work on macOS, while swift-sodium is iOS and macOS (no Catalyst) only, meaning it would work on iOS alone, where you can already use web view based authentication without any fuss...\
I tried implementing it in SwCrypt (without completing it due to lack of time) and it showed some potential (although it's still restricted to OpenCrypto-enabled systems).\
We can totally compare implementations once we're done.

**Comment by MatoMA** [comment]
> Be careful in adding too many dependencies @MatoMA and keep in mind SwiftyRSA does not work on macOS, while swift-sodium is iOS and macOS (no Catalyst, no watchOS, no tvOS, no Linux) only, meaning the feature, and the hole library if it's not packaged in another target, would work on iOS alone, where you can already use web view based authentication without any fuss...
> I tried implementing it in SwCrypt (without completing it due to lack of time) and it showed some potential (although it's still restricted to OpenCrypto-enabled systems).
> We can totally compare implementations once we're done, though.

Thank you very much for your reply.
We found about 1/4 users failing to login with the webview authentication. And it is difficult for us to figure out the issue. This is why we want to make it work for the Android(Device) API.
And it is known that webview authentication not working if the users enable 2FA with Auth App (not text message).
If the above libraries not working, we still have openssl - the last path we'll try...

**Comment by sbertix** [comment]
Web based login not working is just an issue with the current implementation, and it's definitely easier to fix.\
I made it work for [**Swiftagram**](https://github.com/sbertix/Swiftagram), I'll just import the same class in **SwiftyInsta** if the success rate is that bad.\
Either way, having basic authentication back up and working properly is still a priority right now, don't worry 😊

**Comment by sbertix** [comment]
So what do you feel it's the best way to move forward regarding compatibility, @TheM4hd1?\
I've reimplemented `BasicAuthenticator` in [**Swiftagram**](https://github.com/sbertix/Swiftagram), so we could totally translate it for **SwiftyInsta**, but we need to settle on that first (e.g. dropping support for Linux in order for it to work).

**Comment by TheM4hd1** [comment]
@sbertix is it still disabled for you? seems it works again for me now.

**Comment by sbertix** [comment]
I tried it last week and it did not work.\
Apparently it does not affect all accounts but they're migrating it heavily (based on renewed interest on `enc_password` at [**instagram-private-api**](https://dilame/instagram-private-api).\
It should be addressed in **SwiftyInsta** too imho.

**Comment by TheM4hd1** [comment]
what about using `openssl` ? Instagram it self uses `openssl` I guess. this way we can keep the minimum compatibility version and linux compatibility too.

**Comment by sbertix** [comment]
I genuinely hate relying on **OpenSSL** (directly at least) in Swift (like most people hahaha).\
This is definitely "the solution", but I'm not sure implementing it is worth the hassle... @TheM4hd1\
By all means, if you wanna do it, great, otherwise I still feel like going with something "higher level" it's good enough.

**Comment by TheM4hd1** [comment]
I tried implementing `OpenSSL` it works fine on an individual project but adding it as dependency, I wasn't able to do that, cause required lots works and increases the size of library.
If it was my individual project, I'd rather to use it for supporting minimum iOS version. but seems it doesn't worth to do it for library.
So I'm agree with porting `SwiftaGram`, this is the best solution for now.

**Comment by KOSURUUDAYSAIKUMAR** [comment]
Hi, How to get the instagram followers? I downloaded and run the app in iPhone, But it is not calling any functions and methods. Can anyone help me for step by step.

**Comment by sbertix** [comment]
Hey @KOSURUUDAYSAIKUMAR. 
What app are you talking about? 🤔 **SwiftyInsta** is an API wrapper, there's no app to install… 
Please if you need help with the implementation open a new issue. 
I'm hiding this two comments as they're off topic.
