### ISSUE TITLE
Highlights media is empty 

### ISSUE THREAD

**Issue by watergr** [TheM4hd1/SwiftyInsta#187]
When I fetch highlight highlight.item(0) return that they are 6 media but highlight.item(0).media is empty

**Comment by bariscck** [comment]
@watergr I checked it and I am not having any problems right now. Can you share your code block?

**Comment by watergr** [comment]
self.handler.stories.highlightsBy(user: .primaryKey(11830955)) { (result) in
                       switch result {
                       case .success(let medias):
                           print(medias.items[1]) 
                          (print:  "mediaCount": SwiftyInsta.DynamicResponse.number(30))

                           print(medias.items[1].media)
                           (print: [])

                           print(medias.items[1].media.first)
                           (print: nil)

                       case .failure(let err):
                           print(err)
                       }
            }

**Comment by bariscck** [comment]
Ok, I understand the problem. `MediaCount` is returns from directly `Instagram`. `Story` based responses not always populated. This is how `Instagram` api works. Its not related `SwiftyInsta`.
You should call related methods.

In your case your code should be like this;
```
handler.stories.highlightsBy(user: .primaryKey(11830955)) { [weak self] (result) in
            switch result {
            case .success(let tray):
                let identifiers = tray.items.compactMap({ $0.identity.identifier })
                
                self?.handler.stories.reelsMedia(identifiers) { (result) in
                    switch result {
                    case .success(let dict):
                        print(dict)
                    case .failure(let error):
                        print(error.localizedDescription)
                    }
                }
            case .failure(let error):
                print(error)
            }
        }
```
