### ISSUE TITLE
Pod not install

### ISSUE THREAD

**Issue by MariaJsn** [TheM4hd1/SwiftyInsta#189]
When I try to install pod it gives error.

[!] Error installing SwiftyInsta
[!] /usr/local/bin/git clone https://github.com/TheM4hd1/SwiftyInsta.git /var/folders/sm/sb6c02013d78gjqj6hxg1xfc0000gn/T/d20200518-2900-q7jq3j --template= --single-branch --depth 1 --branch 2.3

Cloning into '/var/folders/sm/sb6c02013d78gjqj6hxg1xfc0000gn/T/d20200518-2900-q7jq3j'...
warning: Could not find remote branch 2.3 to clone.
fatal: Remote branch 2.3 not found in upstream origin

**Comment by sbertix** [comment]
Looks like it's trying to fetch a branch named `2.3` instead of version `2.3`.\
Do you mind adding your pod file?

**Comment by TheM4hd1** [comment]
update the pod repo and try installing again, the latest version is `2.3.2`

**Comment by MariaJsn** [comment]
I dod not write version in pod file

my pod is like:  pod "SwiftyInsta"

**Comment by sbertix** [comment]
Did you manage to make it work eventually? @MariaJsn  😊\
I'm closing this cause it appears not to be an error with **SwiftyInsta**.\
Please feel free to comment below again if you need further assistance.
