### ISSUE TITLE
Client is missing required entitlement

### ISSUE THREAD

**Issue by borisdipner** [TheM4hd1/SwiftyInsta#198]
After using login for >= 12 iOS - I got this

20-07-05 13:52:53.524581+0600 InstaPro[15062:971119] [ProcessSuspension]  0x1110fd690 - ProcessAssertion() PID 15062 Unable to acquire assertion for process with PID 15117
2020-07-05 13:52:53.524722+0600 InstaPro[15062:961869] [ProcessSuspension] 0x1110fd690 - ProcessAssertion::processAssertionWasInvalidated()
2020-07-05 13:52:53.526214+0600 InstaPro[15062:971119] [assertion] Error acquiring assertion: <NSError: 0x600000242910; domain: RBSAssertionErrorDomain; code: 2; reason: "Client is missing required entitlement"> {
    userInfo = {
        RBSAssertionAttribute = <RBSLegacyAttribute: 0x7fc1dfc2aac0; requestedReason: FinishTaskUnbounded; reason: FinishTaskUnbounded; flags: PreventTaskSuspend>;
    }
}

**Comment by sbertix** [comment]
Nothing to do with **SwiftyInsta**, per se, it's about background mode.\
Apparently you are using some feature related to it without enabling it from the project settings.\
Go to your target settings, select `Signing & Capabilities` from the tab bar, `+ Capability` and choose the specific background mode you require.

**Comment by borisdipner** [comment]
I made it but still getting this error

**Comment by sbertix** [comment]
I can't seem to replicate this.\
Do you mind providing more info?
