### ISSUE TITLE
Login stopped working

### ISSUE THREAD

**Issue by biox86** [TheM4hd1/SwiftyInsta#201]
Authenticating with cache or via LoginWebViewController fails with error:
"https://i.instagram.com/api/v1/accounts/current_user/.\nInvalid response.\nProcessing handler returned `nil`.\n405"

**Comment by alperalb** [comment]
Change UsersHandler CurrentUser method from post to get

`func current(delay: ClosedRange<Double>?, completionHandler: @escaping (Result<User, Error>) -> Void) {
        guard let storage = handler.response?.storage else {
            return completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response` in `APIHandler.respone`. Log in again.")))
        }
//        let body = ["_uuid": handler.settings.device.deviceGuid.uuidString,
//                    "_uid": storage.dsUserId,
//                    "_csrftoken": storage.csrfToken]
        
        requests.request(User.self,
                         method: .get,
                         endpoint: Endpoint.Accounts.current,
                         //body: .parameters(body),
                         delay: delay,
                         process: { User(rawResponse: $0.user) },
                         completion: completionHandler)
    }`

**Comment by zhangzhewei001** [comment]
I tried it based on your solution, but it doesn't seem to work.

**Comment by zhangzhewei001** [comment]
> Change UsersHandler CurrentUser method from post to get
> 
> `func current(delay: ClosedRange<Double>?, completionHandler: @escaping (Result<User, Error>) -> Void) { guard let storage = handler.response?.storage else { return completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response`in`APIHandler.respone`. Log in again.")))
> }
> // let body = ["_uuid": handler.settings.device.deviceGuid.uuidString,
> // "_uid": storage.dsUserId,
> // "_csrftoken": storage.csrfToken]
> 
> ```
>     requests.request(User.self,
>                      method: .get,
>                      endpoint: Endpoint.Accounts.current,
>                      //body: .parameters(body),
>                      delay: delay,
>                      process: { User(rawResponse: $0.user) },
>                      completion: completionHandler)
> }`
> ```

I tried it based on your solution, but it doesn't seem to work

**Comment by alperalb** [comment]
> > Change UsersHandler CurrentUser method from post to get
> > `func current(delay: ClosedRange<Double>?, completionHandler: @escaping (Result<User, Error>) -> Void) { guard let storage = handler.response?.storage else { return completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response`in`APIHandler.respone`. Log in again.")))
> > }
> > // let body = ["_uuid": handler.settings.device.deviceGuid.uuidString,
> > // "_uid": storage.dsUserId,
> > // "_csrftoken": storage.csrfToken]
> > ```
> >     requests.request(User.self,
> >                      method: .get,
> >                      endpoint: Endpoint.Accounts.current,
> >                      //body: .parameters(body),
> >                      delay: delay,
> >                      process: { User(rawResponse: $0.user) },
> >                      completion: completionHandler)
> > }`
> > ```
> 
> I tried it based on your solution, but it doesn't seem to work

This one is working for me..
If you are using pods, you might need to re-build the project, cleaning all first (command-shift-K) or cleaning derived data.
Changed lines is in UserHandler.swift file, starting on line 13

**Comment by MatoMA** [comment]
> Change UsersHandler CurrentUser method from post to get
> 
> `func current(delay: ClosedRange<Double>?, completionHandler: @escaping (Result<User, Error>) -> Void) { guard let storage = handler.response?.storage else { return completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response`in`APIHandler.respone`. Log in again.")))
> }
> // let body = ["_uuid": handler.settings.device.deviceGuid.uuidString,
> // "_uid": storage.dsUserId,
> // "_csrftoken": storage.csrfToken]
> 
> ```
>     requests.request(User.self,
>                      method: .get,
>                      endpoint: Endpoint.Accounts.current,
>                      //body: .parameters(body),
>                      delay: delay,
>                      process: { User(rawResponse: $0.user) },
>                      completion: completionHandler)
> }`
> ```

Thank you @alperalb , work for me.

**Comment by zhangzhewei001** [comment]
> > > Change UsersHandler CurrentUser method from post to get
> > > `func current(delay: ClosedRange<Double>?, completionHandler: @escaping (Result<User, Error>) -> Void) { guard let storage = handler.response?.storage else { return completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response`in`APIHandler.respone`. Log in again.")))
> > > }
> > > // let body = ["_uuid": handler.settings.device.deviceGuid.uuidString,
> > > // "_uid": storage.dsUserId,
> > > // "_csrftoken": storage.csrfToken]
> > > ```
> > >     requests.request(User.self,
> > >                      method: .get,
> > >                      endpoint: Endpoint.Accounts.current,
> > >                      //body: .parameters(body),
> > >                      delay: delay,
> > >                      process: { User(rawResponse: $0.user) },
> > >                      completion: completionHandler)
> > > }`
> > > ```
> > 
> > 
> > I tried it based on your solution, but it doesn't seem to work
> 
> This one is working for me..
> If you are using pods, you might need to re-build the project, cleaning all first (command-shift-K) or cleaning derived data.
> Changed lines is in UserHandler.swift file, starting on line 13

Thanks, I clear the derived data and it works normally.

**Comment by sbertix** [comment]
Thank you @alperalb , I've updated the code in `2.3.3`.\
Please keep in mind, though, that **SwiftyInsta** is no longer being actively maintained, so while this was an easy fix, it might stop working in the future.

**Comment by biox86** [comment]
Thanks for the fast update. It’s pretty sad that it’s not actively maintained though, imho it is the best swift Instagram framework at the moment and it would be a waste to let it die.

**Comment by mycroftcanner** [comment]
@sbertix happy to help with maintenance. Where is the announcement?

**Comment by mycroftcanner** [comment]
Had to use `pod 'SwiftyInsta', :git => 'https://github.com/TheM4hd1/SwiftyInsta', :branch => 'master'` 

@sbertix is the release tagged?

**Comment by sbertix** [comment]
> Thanks for the fast update. It’s pretty sad that it’s not actively maintained though, imho it is the best swift Instagram framework at the moment and it would be a waste to let it die. 

There were too many "issues" with the current implementation,  requiring a completely clean slate going forward. 

When I wrote **SwiftyInsta** `2.0`, I did it in a way so it'd still be "authentic" to the original implementation, which was basically a porting.

Swift changed a lot since then and a lot of features can simply not be added to the codebase, e.g. cancelling a request, multi-storage support for authentication responses, a username and password authentication, **Combine** support, custom authentication, etc.

So, I started a new project using modern Swift, [**Swiftagram**](https://github.com/sbertix/Swiftagram), to fix all of that cause starting from scratch truly was a necessity.

**Comment by sbertix** [comment]
> @sbertix happy to help with maintenance. Where is the announcement?

No official announcements. I would remind people every once in a while when new issues were sent in.

As I'm working on [**Swiftagram**](https://github.com/sbertix/Swiftagram), I'm still going be to fixing critical issues (like this one), but I won't be pushing new features or enhancements here (for instance I'm not gonna port **Swiftagram** `BasicAuthenticator` for a working non-web view based login, or its **Combine** features).

If you are invested in **SwiftyInsta**, and want to contribute through PRs, and keeping this active, you're more than welcome.

**Comment by sbertix** [comment]
> Had to use `pod 'SwiftyInsta', :git => 'https://github.com/TheM4hd1/SwiftyInsta', :branch => 'master'`
> 
> @sbertix is the release tagged?

Yep. Everything tagged and pod version updated… 🤔 
I'm not sure why it'd do that.
