### ISSUE TITLE
Upload a picture: when will it be fixed

### ISSUE THREAD

**Issue by NathanFallet** [TheM4hd1/SwiftyInsta#206]
Any news about when this will be fixed to be available again? I spent my day writing an app, and I'm stuck on the last step to upload the picture...

https://github.com/TheM4hd1/SwiftyInsta/blob/666bd39673c9d7bc1bb288b633de9f9e1089cc8a/SwiftyInsta/API/Handlers/MediaHandler.swift#L114

**Comment by sbertix** [comment]
**SwiftyInsta** is no longer being actively maintained, so it most likely won't unfortunately.\
I haven't come up adding it in [**Swiftagram**](https://github.com/sbertix/Swiftagram) either yet, so if I don't it there, there's little chance it'll be ported back to **SwiftyInsta**.

Please check out #204. 

_In case somebody decides to work on this, they can simply reopen the issue, but this won't be added for now._

**Comment by NathanFallet** [comment]
@sbertix I made some searches this morning, and I made a HAR recording of HTTP requests when uploading a media to Instagram. How can I contact you to talk about it, and if we find something with it I will try to create a PR to solve this issue? (I didn't find any other contact method on your GH profile, so I responded to this issue)

**Comment by sbertix** [comment]
telegram.me/sbertix @NathanFallet 

I can't promise I can make it work for **SwiftyInsta**, it's definitely something I'll look into for [**Swiftagram**](https://github.com/sbertix/SwiftyInsta), though.
