### ISSUE TITLE
Access getMediaLikers items

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#21]
I am trying to get media likers . Function is working nice and I can see the results with breakpoint. But when I try to get items in model I can not access it.

my codes:

let users = result.value.map({ $0.users! }) -> It gives an error like 'users' is inaccessible due to 'internal' protection level

and I try to access it with: 
result.value.users -> It says Value of type 'MediaLikersModel?' has no member 'users'

How can I get the users who like media?

**Comment by TheM4hd1** [comment]
issue fixed, please update to latest version ```1.0.0```
let me know if any other issues exists.

**Comment by flamme0011** [comment]
yeap it is working thanks
