### ISSUE TITLE
Login WebView app crashed in Swift

### ISSUE THREAD

**Issue by KOSURUUDAYSAIKUMAR** [TheM4hd1/SwiftyInsta#212]
Hi Team,

When I install the pod and run the project. I gave LoginWebViewController as an storyboard inside class name: But the app is crashed :
![Screenshot 2020-08-29 at 6 54 06 PM](https://user-images.githubusercontent.com/28728191/91637862-1380fa80-ea29-11ea-844e-b9deb443aa8b.png)

Instagram[469:27074] Fatal error: init(coder:) has not been implemented: file /Users/My/Desktop/Instagram/Pods/SwiftyInsta/SwiftyInsta/UI/LoginWebViewController.swift, line 68

I have an requirement please help me anyone.

**Comment by sbertix** [comment]
You should not use `LoginWebViewController` directly in your storyboard.\
Just initiate it in your code and then present it as a modal 💪
