### ISSUE TITLE
How to get Access token after user logs in to instagram?

### ISSUE THREAD

**Issue by AwaisFayyaz** [TheM4hd1/SwiftyInsta#215]
I have checked the `Authentication.response` but could not find a property through which i can get my hands on access Token? is this possible with Swifty Insta to get Access token after the login?

**Comment by borisdipner** [comment]
Save it somewhere. In the readme you can find ex how to store it in user defaults.

**Comment by sbertix** [comment]
Hey @AwaisFayyaz,

You should use `.persist()` on your `Authentication.Response`, save the returned `String` in `UserDefaults` (or similar), and then use that string to retrieve the response on your next launch with `Authentication.Response.persisted(with:)`. 

Although easier, **you should not** follow @borisdipner's advice: storing cookies in `UserDefaults` should be avoided at all costs, being a serious security concern. 
I also know the `README.md` suggests that (I wrote that so I know hahaha), but please don't do it.

**Comment by AwaisFayyaz** [comment]
Hi @sbertix . Thanks for the reply.
I am already using the `.persist()` function from the sample code on readme with heading LoginWebViewController (>= iOS 12 only) and its working fine. I can get the user details and followers. APIs seem to be working fine.

I am looking to get access token after the login which looks something like this 
IGQVXXXXXXXXXXXpsVnhPcjJoLUZApdUFSdHFjc1FOdmN2QU1mT2ZAYdnBqd2x2NDcxRXFUN3ZAQLUZAuVzFUNkVQMGlOYmRHeEQ4ZADM1RExlWUJMblowZAzhPbDRFRXV4Q3ZAkRG9DR0NVMjM2ejRDQUQ5MkFCVXXXXXXXXXXX.

I need to send this access token to Backend. But could not find any property which gives me the access token. am i missing something?

**Comment by TheM4hd1** [comment]
`SwiftyIntsa` uses Private API, `access_token` belongs to to official API. The Private API is the one that Instagram's app is using. It's the reversed version of official app's api

**Comment by AwaisFayyaz** [comment]
Thanks for the reply @TheM4hd1 
Any way i can get my hands on access token using this private API?

**Comment by TheM4hd1** [comment]
Private API doesn't rely on `access_token`, so No, there is no way to get `access_token` since it's doesn't exists in private api

**Comment by AwaisFayyaz** [comment]
Thanks for the clarification @TheM4hd1 .
Much appreciated
