### ISSUE TITLE
Can you help me. – "status" : "fail"

### ISSUE THREAD

**Issue by devbitsman** [TheM4hd1/SwiftyInsta#218]
Can you help me.
After authorization, I do any actions, for example "follow" and an error always comes out:

"We limit how often you can do certain things on Instagram, like unfollowing people, to protect our community. Tell us if you think we made a mistake."

but I do not do any other actions before that except authorization.

**Comment by TheM4hd1** [comment]
Hello,
what version of lib are you using?
the issue has fixed in #214

**Comment by devbitsman** [comment]
I am using the latest version 2.4
Sometimes, after authorization, it is possible to send one action, for example, follow. And on the next steps, an error is already generated. Even if you wait 5 minutes.

**Comment by TheM4hd1** [comment]
I'm afraid that this not the lib's issue, but for further investigation please contact me.
You can find my email in the profile page.

**Comment by devbitsman** [comment]
maybe there is a limit to the number of actions in a period of time? Some kind of interval between actions?

**Comment by TheM4hd1** [comment]
of course there's a limit, but it shouldn't happen immediately for you, unless your account has reached maximum daily limits or your account marked as spam.
it's about:

- 100-150 follow/unfollow per day
- 300-400 likes per day
- 20-30 comments per day 

so to be organic and look real, you need to send an action every 30-40 seconds.
in total a normal account (an account with age of more than 3 month) can send 500-1000 requests daily (includes login, fetching data and ..) it depends on age of account.
