### ISSUE TITLE
Realtime Data for Notifications, etc.

### ISSUE THREAD

**Issue by RealOlympusDev** [TheM4hd1/SwiftyInsta#22]

**Comment by sbertix** [comment]
Hey @RealOlympusDev 😊 
Do you mind expanding a bit on what you mean by "Realtime Data for Notifications, etc."? To understand whether it's something that can actually be implemented, maybe even for `2.0`, which is currently in development, or not.
Thanks 💪

**Comment by RealOlympusDev** [comment]
Look at mgp25's version: 

https://github.com/mgp25/Instagram-API/tree/master/src/Realtime
https://github.com/mgp25/Instagram-API/blob/master/examples/pushReceiver.php

I believe they use Mqtt. To get messages, notifications, etc. (I doesn't use the actual apns).

**Comment by sbertix** [comment]
Ok so it's actually closer to "streams", as I suspected.

Unfortunately, both `Push` and `Realmtime` in `mpg25` are inconsistent, and (the public versions at least) have not been maintained in several years.
(e.g. [one of the many issues stating they're unreliable](https://github.com/mgp25/Instagram-API/issues/2380))

Browsing through PR and issues in the past, it seems like the best scenario would be replicating the `Realtime` `loop` manually, forcing the request as time goes by (which is inconvenient, I agree).
Right now it appears to be the only 100% future-proof solution, and super easy to add to any `endpoint`, but I feel like it should be left to people using the library to implement it of their own accord.

**Comment by sbertix** [comment]
But please, feel free to submit a _pull request_ in case you come up with either a "fix" for `Push` and `Realtime` or an alternative solution to evaluate 💪 @RealOlympusDev
