### ISSUE TITLE
Follow and Unfollow methods are not working.

### ISSUE THREAD

**Issue by ahmetkocu** [TheM4hd1/SwiftyInsta#223]
Hi,

I am using your library and I am developing an iOS app.

I try to follow or unfollow users but not working this methods.

Can you check these methods?

**Comment by TheM4hd1** [comment]
Hello,
methods are fine and updated with latest instagram changes.
read here: https://github.com/TheM4hd1/SwiftyInsta/issues/218

**Comment by ahmetkocu** [comment]
Hi,

I know all api changes, I developed an android app and published it. Everything is working good. 

Also I know about api limits.

However when I can make follow or unfollow in my android app, with your latest version of library, I can not do that.

I simply add as a pod and call your methods like you describe.

I can not understand what is the problem.

**Comment by TheM4hd1** [comment]
it may be related to user-agent.
check the other library, and update this issue please.
https://github.com/sbertix/Swiftagram

**Comment by ahmetkocu** [comment]
I think your should sign follow and unfollow request with igSignatureValue.
and you should send ig_sig_key_version in request body.

**Comment by ahmetkocu** [comment]
I checked that library and they sign the body excatly I do in my android code.

https://github.com/sbertix/Swiftagram/blob/d2016870a2184d72ce951523cc02406000b83e5d/Sources/SwiftagramCrypto/Extensions/Crypto.swift

You should check here.

**Comment by TheM4hd1** [comment]
there is no need to sign the requests with signature key in recent versions.

**Comment by ahmetkocu** [comment]
Yes, you are right, I checked it.

However I can not achieve follow action with your library.

**Comment by sbertix** [comment]
It is indeed related to the user agent. It's a long known issue with **SwiftyInsta**. 
Basically, authentication cookies and actual API requests are not mocked to be fetched by the same device, so some endpoints automatically fail, like these ones. 
Adjusting the user agent for the web view authenticator in your code so that it matches the device used for all other requests, and logging back in should to the trick @ahmetkocu.

**Comment by ahmetkocu** [comment]
Hi, 

In this library, it can be fixed I think.

I checked the user agent that is for API call, these are android device brands and models. However in loginwebview, using a different user agent, it is iphone device.

**Comment by sbertix** [comment]
Sure it can be fixed :blush: 

If you wanna work on a fix you can just port [**Swiftagram**](https://github.com/sbertix/Swiftagram)'s implementation here. 
You have my blessings 💪

**Comment by TheM4hd1** [comment]
check the [development ](https://github.com/TheM4hd1/SwiftyInsta/tree/development)branch, I added a temporary way, lmk if it fixed your problem.
