### ISSUE TITLE
Get users tagged in media

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#224]
Is it possible to get the users tagged in media, like stories?

The private API from go seems to have something: https://godoc.org/github.com/ahmdrz/goinsta#Item

![Screenshot 2020-12-04 at 16 05 08](https://user-images.githubusercontent.com/55385694/101186112-8f9f6580-364a-11eb-8b0f-528ed1e823aa.png)

![Screenshot 2020-12-04 at 16 05 42](https://user-images.githubusercontent.com/55385694/101186226-b65d9c00-364a-11eb-8b51-89a8167c8d21.png)

**Comment by sbertix** [comment]
Hey @mycroftcanner, 

if I understand correctly, you're trying to parse tagged users in a `Media` instance, correct? 
Then given your `media` you can just do…

```swift
let media: Media = /* some `Media` */
let taggedUsers = media.rawResponse.usertags.array
```

… and then either parse the `DynamicResponse`s in `taggedUsers` into a `struct` or use them directly.
:blush:
