### ISSUE TITLE
get all followed user , spend too time

### ISSUE THREAD

**Issue by tomtao88888** [TheM4hd1/SwiftyInsta#225]
handler.settings.delay = 0...0
handler.users.followed(byUser: .me,
                                       with: .init(startingAt: self.nextMaxId, maxPagesToLoad: .max),

    I use this code get all followed user ,  about 500 peoples, but spend
 9-10 seconds,  it’s slow,

   I saw a iOS app with other instagram private api  , get 500 followed user , only 2-3 seconds.  Can we  optimization it?

**Comment by sbertix** [comment]
Hey @tomtao88888,

To achieve those speeds you would actually need to scrape the Instagram mobile web page, that's how most apps do it.
You can set it up pretty easily with a background `WKWebView` and injecting it the authentication cookies you get from **SwiftyInsta**. 
So to answer your question, no: there's no way to make it faster **using the Instagram Private API**. 

Also, keep in mind that setting the delay to `0` to your `handler.settings`, especially for followers and following, will result in the account being marked as spam, so try and avoid it.

**Comment by tomtao88888** [comment]
i used web  method login instagram
about "You can set it up pretty easily with a background WKWebView and injecting it the authentication cookies you get from SwiftyInsta."  ,  i  don't understand.
what's should i do ?

i saw this in the code

![image](https://user-images.githubusercontent.com/57318332/101889854-db1dba80-3bda-11eb-967b-59b93ae369b1.png)

**Comment by sbertix** [comment]
Sorry for the delay, I did not get notified for some reason. 

**SwiftyInsta** does not provide scraping functionality, it's just a wrapper for the Private API. 
You would need to implement it yourself, but it's gonna be the best solution for what you need.
