### ISSUE TITLE
User.counters don't working

### ISSUE THREAD

**Issue by borisdipner** [TheM4hd1/SwiftyInsta#226]

**Comment by borisdipner** [comment]
Using SwiftyInsta 2.3.9

**Comment by borisdipner** [comment]
user?.followingCount and etc shows nil values

**Comment by borisdipner** [comment]
Using it like this 
      handler.authenticate(with: .cache(cache)) { response in
            switch response{
                case .success(let data):
                    let userFromData = data.1.user?.followingCount // nil
                    let userFromData2 = data.0.user?.followingCount // nil

**Comment by TheM4hd1** [comment]
Instagram changed the data from the[ `current`](https://github.com/TheM4hd1/SwiftyInsta/blob/cc4baefe10bfdf6a147cc7b6082395f2bd6794a4/SwiftyInsta/API/Handlers/UserHandler.swift#L16) endpoint, you can call [`user(primaryKey)`](https://github.com/TheM4hd1/SwiftyInsta/blob/cc4baefe10bfdf6a147cc7b6082395f2bd6794a4/SwiftyInsta/API/Handlers/UserHandler.swift#L109) for now until we updated the function with another endpoint.

**Comment by fridayhoney** [comment]
Hey 👋 
Still not fixed ?

**Comment by kevinlieser** [comment]
Can also not fetch the followerCount
`self.handler.users.user(.primaryKey(self.handler.user!.identity.primaryKey!)) { data in
           print(data)
}`

Data comes but nothing like followerCount. Any ideas?

**Comment by sbertix** [comment]
Hey @borisdipner and @kevinlieser,
please refer to #244 about the future of **SwiftyInsta**.
