### ISSUE TITLE
Upload Profile Picture Not Working

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#230]
Uploading profile pictures doesn't seem to be working, I am passing a simple UIImage.

The error:

> "https://i.instagram.com/api/v1/accounts/change_profile_picture/.\nInvalid response.\nProcessing handler returned `nil`.\n400"

Could this be related to the authentication causing problems as mentioned in other issues?

```swift
      self.upload(
        profilePicture: .init(
          image: image,
          caption: "A",
          size: .init(width: 320, height: 320)
        )
      ) { result in
        switch result {
        case .success:
          promise(.success(true))
        case let .failure(error):
          promise(.failure(error))
        }
      }
```

**Comment by sbertix** [comment]
Hey @mycroftcanner,

I haven't tested it and I seem to remember this wasn't one of the updated endpoints, so it might not be working, simply cause it's not supposed to...

But. Does the upload succeeds when not setting a caption? Does your image have an alpha layer? What's the aspect ratio? And the color space?
Cause those tend to be the issues most of the time.

**Comment by TheM4hd1** [comment]
Seems other upload functions stopped working again. I'm receiving this error:
`{"debug_info":{"retriable":false,"type":"ParameterValidationError","message":"Header Content-Length has invalid value"}}`
`content-length` seems to be fine, even with the compression amount which defined in `X-Instagram-Rupload-Params` header
gonna look more to find the issue.

**Comment by mycroftcanner** [comment]
> But. Does the upload succeeds when not setting a caption? Does your image have an alpha layer? What's the aspect ratio? And the color space?

Hey @sbertix !

Thanks for your reply, I tried all your suggestions, still no luck unfortunately :/

**Comment by TheM4hd1** [comment]
The endpoint needs to be updated, it doesn't work with old implementation.
I'll try to push a PR in near future.

**Comment by sbertix** [comment]
Hey @mycroftcanner, 
please refer to #244 about the future of **SwiftyInsta**.
