### ISSUE TITLE
how to get followedBy via  friendships / show_many ?

### ISSUE THREAD

**Issue by tomtao88888** [TheM4hd1/SwiftyInsta#231]
There can be a lot of followers and sending 1 request per 1 person looks scary, it seems to me if I send it so 1000+ insta requests will be banned
How to be use "/ friendships / show_many /" but there is not complete information about mutual subscription

 it works now. But there is still one problem.
Here is the json form of the friendship status

{
  "following" : true,
  "incomingRequest" : false,
  "isBestie" : true,
  "isPrivate" : true,
  "isRestricted" : false,
  "outgoingRequest" : false
}
Can't recevie followedBy. I think instagram changed the structure

**Comment by sbertix** [comment]
Hey @tomtao88888,

If you're asking just to know whether users you follow, follow you back or viceversa, the quickest and most robust way is actually fetching all followers, fetching all following, and then comparing them locally. 
It's future proof and it does not rely on endpoints which are not really tested in terms of "spam limits".

**Comment by tomtao88888** [comment]
> Hey @tomtao88888,
> 
> If you're asking just to know whether users you follow, follow you back or viceversa, the quickest and most robust way is actually fetching all followers, fetching all following, and then comparing them locally.
> It's future proof and it does not rely on endpoints which are not really tested in terms of "spam limits".
> 
> If you still just prefer to inspect the response for changed properties, though, remember you can always access the underlying `Response` of the model.

but  i follower 16,000 users,  following 7000 users,   if fetching all followers and following , will be spent more time

**Comment by sbertix** [comment]
Like I said, then you can still rely on `/friendship/show_many/` and deal with the raw response instead of the parsed model. 
Use `friendship.rawResponse` and inspect non-exposed properties for values that might have changed.
