### ISSUE TITLE
can we set Number of users returned per page?

### ISSUE THREAD

**Issue by tomtao88888** [TheM4hd1/SwiftyInsta#232]
I used followed get my following users , default got 50 users per page.

 handler.users.followed(byUser: .me,
                               with: .init(startingAt: nextMaxId, maxPagesToLoad:  1),

can we set Number of users returned per page?
such as  return  100 or  200 users per page!

**Comment by sbertix** [comment]
Hey @tomtao88888,

No you cannot, unfortunately. 
The endpoint doesn't seem to allow for a "page length" parameter so you cannot find it here either.
