### ISSUE TITLE
Highlights media is empty

### ISSUE THREAD

**Issue by akoruk** [TheM4hd1/SwiftyInsta#234]
StoryHandler highlightsBy method returns the list of highlights, but media list is empty. There seems no other method for a single highlight details by highlight id.

**Comment by sbertix** [comment]
Hey @akoruk,

Highlights, as well as most of tray items in general, are only ever populated on demand. 
Once you get the identifier of the highlight you should pass it to `StoryHandler.reelsMedia` and observe its content that way 💪
