### ISSUE TITLE
Unable to login due to missing header

### ISSUE THREAD

**Issue by jsantolaria** [TheM4hd1/SwiftyInsta#236]
Hi, 
I am unable to login with web view because server never returns me the 'ig-set-authorization' header.
It seems to be ok if I comment it (authenticationHandler l.44) but, I suspect it to cause troubles with some requests (mark story as seen disconnects me).

An idea how to solve it properly ?

**Comment by sbertix** [comment]
Hey @jsantolaria, 
please refer to #244 about the future of **SwiftyInsta**.
