### ISSUE TITLE
How do I get the URL of the video type Media?

### ISSUE THREAD

**Issue by zhangzhewei001** [TheM4hd1/SwiftyInsta#238]
I'm a newbie, I want to use this API to get some information, but I found that I can't get the URL of the Media of the video type, it only returns the thumbnail of the Video, but I found that there is a video of Media in this project. If you know how to use it, please let me know, thank you very much!

**Comment by sbertix** [comment]
Hey @zhangzhewei001, 
please refer to #244 about the future of **SwiftyInsta**.
