### ISSUE TITLE
LoginWebViewController can't login

### ISSUE THREAD

**Issue by tomtao88888** [TheM4hd1/SwiftyInsta#239]
let login = LoginWebViewController { controller, result in
    controller.dismiss(animated: true, completion: nil)
    // deal with authentication response.
    guard let (response, _) = try? result.get() else { return print("Login failed.") }

return "Login failed.

**Comment by tomtao88888** [comment]
ios 13
sometimes return "Invalid `Authentication.Response` 
sometimes return login successful

**Comment by tomtao88888** [comment]
something web login return  "Invalid Authentication.Response,  i tracked , in here
I guess web cookies not return because of network speed
any idea ?

case .success(let instagramCookies):
                    let data = instagramCookies.filter({ $0.domain.contains(".instagram.com") })
                    let filtered = data.filter { $0.name == "ds_user_id" || $0.name == "csrftoken" || $0.name == "sessionid" }
                    guard filtered.count >= 3 else {
                        return handler.settings.queues.response.async {
                            **_completionHandler(.failure(GenericError.custom("Invalid `Authentication.Response` response.")))_**
                        }
                    }

**Comment by tomtao88888** [comment]
sometimes instagramCookies just return csrftoken
not ds_user_id and sessionid
any idea?

**Comment by borisdipner** [comment]
R u trying to login on simulator?

**Comment by sbertix** [comment]
Hey @tomtao88888 and @borisdipner, 
please refer to #244 about the future of **SwiftyInsta**.
