### ISSUE TITLE
PaginationParameters.nextMaxId always nil when querying Inbox

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#241]
Hey all,

In the completion handler of the `inbox` method all properties of `PaginationParameters` are set to their default value.

```swift
public typealias PaginationCompletionHandler<R> = (_ response: Result<[R], Error>, _ nextParameters: PaginationParameters) -> Void
```

```swift
public func inbox(with paginationParameters: PaginationParameters,
                      updateHandler: PaginationUpdateHandler<Thread, AnyPaginatedResponse>?,
                      completionHandler: @escaping PaginationCompletionHandler<Thread>) {
        pages.request(Thread.self,
                      page: AnyPaginatedResponse.self,
                      with: paginationParameters,
                      endpoint: { Endpoint.Direct.inbox.next($0.nextMaxId) },
                      splice: { $0.rawResponse.inbox.threads.array?.compactMap(Thread.init) ?? [] },
                      update: updateHandler,
                      completion: completionHandler)
    }
```

```swift
import Foundation

public class PaginationParameters {
    /// The maximum number of pages to load. Defaults to `1`.
    public var maxPagesToLoad: Int
    /// The number of pages already loaded. Defaults to `0`.
    public var loadedPages: Int = 0
    /// The current request `maxId`. Defaults to `nil`.
    public var currentMaxId: String?
    /// The next `maxId`. Defaults to `nil`.
    public var nextMaxId: String?

    /// Whether there's something left to load.
    var canLoadMore: Bool { return loadedPages < maxPagesToLoad }

    // MARK: Init
    public init(startingAt maxId: String? = nil, maxPagesToLoad: Int = 1) {
        precondition(maxPagesToLoad > 0, "`maxPagesToLoad` must be bigger than `0`.")
        self.nextMaxId = maxId
        self.maxPagesToLoad = maxPagesToLoad
    }
    public init(_ paginationParameters: PaginationParameters) {
        self.nextMaxId = paginationParameters.nextMaxId
        self.maxPagesToLoad = paginationParameters.maxPagesToLoad
    }
    public static let everything = PaginationParameters(startingAt: nil, maxPagesToLoad: .max)

    // MARK: Obsolete
    @available(*, unavailable, message: "use `init` instead.")
    public static func maxPagesToLoad(maxPages: Int) -> PaginationParameters {
        fatalError("`maxPagesToLoad(maxPages:)` was removed.")
    }
}
```

If anyone has any idea what the issue might be I would be happy to try and patch a fix.

Thanks.

**Comment by sbertix** [comment]
Hey @mycroftcanner, 

The cursor is now nested inside the main object, that's the reason why it always returns `nil`. 
I'm not sure anyone is still maintaining this repo, but I'm more than happy to merge a PR if you wanna work on it (you can also use **Swiftagram** as the starting point, I don't mind).

**Comment by mycroftcanner** [comment]
I don't understand what you mean by nested inside the main object. I have been thinking of switching to Swiftagram. I need to check if everything we are using from SwiftyInsta is available in Swiftagram.

**Comment by sbertix** [comment]
> I don't understand what you mean by nested inside the main object.

The "next identifier" is no longer a property to the root object, but it's nested inside "inbox". 

```
{
   "inbox": {
      "oldest_cursor": "/* the next identifier */",
      […]
   },
   […]
}
```

I don't remember correctly cause it's been a long time since I wrote `PagerHelper`, but there should be a `next` argument in the `request` method in your second comment block where you can refer to the moved "oldest_cursor".

**Comment by mycroftcanner** [comment]
> I don't remember exactly, cause it's been a long time since I wrote `PagerHelper`, but there should be a `next` argument in the `request` method (in your second comment block), where you can refer to the moved "oldest_cursor".

Thanks so much, I managed to fix it. I'll submit a pull request later :) 

> (you can also use **Swiftagram** as the starting point, I don't mind).

Btw I noticed cursoring already works correctly in Swiftagram 👍

I also wanted to implement the `pendingInbox` functionality that you have in **Swiftagram**. Any pointers on how to get started?

Cheers,

**Comment by sbertix** [comment]
> Btw I noticed cursoring already works correctly in Swiftagram 👍

Yep, I fixed it when it first broke a couple months ago. 

> I also wanted to implement the pendingInbox functionality that you have in Swiftagram. Any pointers on how to get started?

The endpoint definition is **Swiftagram** is pretty straightforward so you should have no issues in porting it to **SwiftyInsa** 💪
