### ISSUE TITLE
/feed/reels_media/

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#25]
Great repo.
Is there any way we could have story highlights added as well?

**Comment by TheM4hd1** [comment]
make sure update to version `1.0.5`

**Example**:
https://github.com/TheM4hd1/SwiftyInsta/blob/10db0b97b7508a5c492c9f178c35b63768b2811b/SwiftyInstaTests/SwiftyInstaTests.swift#L1330

**Comment by sbertix** [comment]
Great!
Unfortunately it does not seem to populate items for every Higlight, only the first one, and not reliably either.
Quickly googling it seems to suggest that to retrieve the actual items (i.e. stories) we need to pass the id to the "reels_media" endpoint. Any plans to add that as well?
Thanks @TheM4hd1

**Comment by TheM4hd1** [comment]
did you try passing ID like this? `highlight:123882132324123`

**Comment by TheM4hd1** [comment]
I see, I'll check it for you.

**Comment by sbertix** [comment]
Thanks man

**Comment by TheM4hd1** [comment]
There is an endpoint: `/feed/reels_media/`
it accepts an array of `user_ids` like `highlight:123882132324123`
I've tried to implement it but I'm receiving an error from server
```json
{"message": "Invalid reel id list", "status": "fail"}
```

try it yourself, see if you can fix it, maybe I'm doing wrong somewhere.

**Comment by sbertix** [comment]
> ```json
> {"message": "Invalid reel id list", "status": "fail"}
> ```

I have to admit that I've been trying to implement this for a while, without success. I was hoping you would fare better, but we seem to have stumbled on the same error unfortunately.

**Comment by TheM4hd1** [comment]
I'l let you know if I find anything, but as I see similar libraries used this endpoint but I didn't test them to see if they works or not.
maybe we're missing something... idk

**Comment by canaksoy** [comment]
I try with "supported_capabilities_new" but same response. anyone fixed?

**Comment by canaksoy** [comment]
sample request

POST:  https://i.instagram.com/api/v1/feed/reels_media/
DATA: signed_body=bca1cf35fe840d851d3d37f488665e955fa517e06a521843b619fd44183e28e3.{"supported_capabilities_new":"[{\"name\":\"SUPPORTED_SDK_VERSIONS\",\"value\":\"9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,28.0,29.0,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,42.0,43.0\"},{\"name\":\"FACE_TRACKER_VERSION\",\"value\":\"10\"},{\"name\":\"segmentation\",\"value\":\"segmentation_enabled\"},{\"name\":\"WORLD_TRACKER\",\"value\":\"WORLD_TRACKER_ENABLED\"}]","source":"feed_timeline","_csrftoken":"lQElejwdXHJToUUryVZWghOEN2X8GFn0","user_ids":["archiveDay:17960651299222776"],"_uid":"5889897609","_uuid":"1df4e0f8-fc98-4250-a6a4-56b455e75699"}&ig_sig_key_version=4

**Comment by canaksoy** [comment]
@TheM4hd1 how can we create signed_body with array inside. how to know which part will be sign?

**Comment by TheM4hd1** [comment]
@canaksoy 
Here is an example of how to sign body.
https://github.com/TheM4hd1/SwiftyInsta/blob/c2beaad164a49b84fe8254af25ac75e36e192f72/SwiftyInsta/API/Services/UserHandler.swift#L164

The sample request you attached above, is it a working version?

**Comment by canaksoy** [comment]
I tried with signed_body samples but its hard to handle [String] with encoder. Yes its a working php sample. @TheM4hd1

**Comment by TheM4hd1** [comment]
@canaksoy 
Okay, I'll check it.
Thanks.

**Comment by TheM4hd1** [comment]
I tested function with 2 id, if you see there are some missing data in returned model, you can decode the returned data to access full info about request.
