### ISSUE TITLE
handler.requests is nil 

### ISSUE THREAD

**Issue by jigneshchovatiya** [TheM4hd1/SwiftyInsta#251]
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file SwiftyInsta/APIHandler.swift, line 19 
While getting user story

**Comment by jigneshchovatiya** [comment]
@sbertix
Please can you help me in solved above issue ?

**Comment by sbertix** [comment]
@jigneshchovatiya you need to retain your APIHandler. 

Closing as this is not a bug, you've just implemented it wrong.

**Comment by jigneshchovatiya** [comment]
let handler = APIHandler()
        handler.authenticate(with: .cache(cache))
        { _ in
            handler.stories.by(user: .username(username)) { (result) in
                print("\(result)")
            }
        }

This is my code after login hows its works
