### ISSUE TITLE
Enum cases with associated values cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#255]
Xcode Version 13 Beta 5

https://bugs.swift.org/projects/SR/issues/SR-14878?filter=allissues

> Robert Widmann added a comment - 7 Jul 2021 10:28 AM
> This is intentional. The ABI of enum cases with payloads that are potentially unavailable is not well-defined. That this worked in the past was by coincidence of your application not requiring the (potentially unavailable) type metadata for the payload. Please either increase your deployment target or mark Foo itself as available as the least-available case.
> https://github.com/apple/swift/pull/36327

**Comment by sbertix** [comment]
Hey @mycroftcanner, 
as this appear to be intended behaviour and not just a beta bug (at least as from the post you've shared), this would require rewriting the affected code. 
As the library is no longer maintained, I doubt this is gonna happen. I'll try and contact @TheM4hd1, if he does not get notified of this discussion, and consider all available options… at this point, as **SwiftyInsta** has severely lagged behind current Instagram APIs, and nobody seems interested in rewriting it from the grounds up, the way I built `2.0` from scratch, archiving the repo seems the better one, imho.

**Comment by sbertix** [comment]
Please check out the updates on #244 @mycroftcanner
