### ISSUE TITLE
Authorization has stopped working!

### ISSUE THREAD

**Issue by devbitsman** [TheM4hd1/SwiftyInsta#258]
Authorization has stopped working, while it works on the site and in the original application. What could be the problem?
![IMG_7CA465E76020-1](https://user-images.githubusercontent.com/61158956/153470835-4e33d8a6-ab0c-4ec8-9125-2edec7c3b902.jpeg)

**Comment by AhmedShammala** [comment]
+1 :(

**Comment by AhmedShammala** [comment]
@devbitsman  any luck on finding the reason for this ?
