### ISSUE TITLE
Story Method

### ISSUE THREAD

**Issue by VetalSkri** [TheM4hd1/SwiftyInsta#26]
There is no method to view the history, so that it is marked as viewed. How I can do this?

**Comment by TheM4hd1** [comment]
make sure update to version `1.1`

```swift
try! handler.markStoriesAsSeen(items: items, sourceId: nil, completion: { (result) in
    if result {
        //...
    } else {
        // ..
    }
})
```

**Comment by VetalSkri** [comment]
You can sample items parameters?


> 22 июня 2019 г., в 21:35, Mahdi Makhdumi <notifications@github.com> написал(а):
> 
> try! handler.markStoriesAsSeen(items: items, sourceId: nil, completion: { (result) in
>     if result {
>         //...
>     } else {
>         // ..
>     }
> })
>

**Comment by TheM4hd1** [comment]
```swift
try! handler.getUserStory(userId: user.value!.pk!, completion: { (result) in
    
    let items = result.value!.items!
    try! handler.markStoriesAsSeen(items: items, sourceId: nil, completion: { (result) in
        exp.fulfill()
    })
//....
```

**Comment by VetalSkri** [comment]
I have errors 

> 22 июня 2019 г., в 21:40, Mahdi Makhdumi <notifications@github.com> написал(а):
> 
> try! handler.getUserStory(userId: user.value!.pk!, completion: { (result) in
>     
>     let items = result.value!.items!
>     try! handler.markStoriesAsSeen(items: items, sourceId: nil, completion: { (result) in
>         exp.fulfill()
>     })

**Comment by TheM4hd1** [comment]
Describe what you doing
Describe steps
Attach your code
Attach screenshot

**Comment by VetalSkri** [comment]
Step one
1) In first, I’m login in my account, with support Siwa ( Very good work )
2) I have a button on my storyboard -> Func fetch request ( down )



3) When a put a button, call func testGetUserStory ( return a user id ) 
4) Func mark is called, if result = true, and in func mark ( I put new request ( markAsSeen )

**Comment by TheM4hd1** [comment]
you didn't attached the info I requested. I can't help you when I don't know what your error is.
1. try to find `userId` of the user you want receive stories from.
2. call `handler.getUserStories` function
3. extract `Items: [TrayItems]` from result you receive in `step 2`
4. call `handler.markStoriesAsSeen` function to mark stories as seen.

If you had any error, please attach the code + screenshots and error.

**Comment by VetalSkri** [comment]
I do) did you get my screenshots? I sort of described everything

**Comment by TheM4hd1** [comment]
No, there is no screenshot here.
Send them to my email.

**Comment by VetalSkri** [comment]
Step one
1) In first, I’m login in my account, with support Siwa ( Very good work )
2) I have a button on my storyboard -> Func fetch request ( down )
3) When a put a button, call func testGetUserStory ( return a user id ) 
4) Func mark is called, if result = true, and in func mark ( I put new request ( markAsSeen )

**Comment by VetalSkri** [comment]
Did you get?
