### ISSUE TITLE
New maintainers or fork?

### ISSUE THREAD

**Issue by mycroftcanner** [TheM4hd1/SwiftyInsta#263]
I don't understand why @sbertix keeps saying that the project is closed and won't approve  any more changes while promoting every time a competing library that lacks a lot of functionalities.

We'll be happy to take over or fork this repo

**Comment by sbertix** [comment]
Nothing of sorts. It's the open source world we're talking about. 
Nobody is silencing you, and I have no monetary gain by suggesting either **SwiftyInsta**, for which I wrote and maintained versions `2.*`, as you well know, or **Swiftagram**. 

We called for maintainers for a long time and nobody answered. 
The notice that's behind every issue and PR is a statement understood with Mahdi cause at the time, I was actively maintaining **Swiftagram** (and I'm planning on doing it again soon) and it was to give all of you, using the repo, something that wasn't stale. 

The architecture of **SwiftyInsta** is simply too old to be worth "fixing", in our understanding, and neither of us had the time to deal with it. 
Maintaining this takes a lot of time, time we're giving away for free. 
This doesn't mean you can't make use of this or even try and make it better by forking this: it simply means "don't expect this to be usable and don't expect it to not be problematic, cause nobody is watching: use it at your own risk".  

As for missing functionality, I'm not really sure what you're referring too, but with **Swiftagram** already featuring better multiuser support, and things like automatic `async`, **Combine** and completion handling coming with `6.0.0`, you need to understand why investing time on this is not viable to us.
