### ISSUE TITLE
Adding Multiple Accounts

### ISSUE THREAD

**Issue by mkeshnoda** [TheM4hd1/SwiftyInsta#27]
Ciao 

I am trying to add multiple account feature. 
What i am trying to do is basically: **Save cookies with user defaults with the key userPk**

But the problem is, when i am trying to add 2nd user,  it brings back first user's cookies 
(somehow and although i delete all cookies) it shows me first user's feed.... So i can't even login for the second user

Any idea on how to fix this?

**Comment by TheM4hd1** [comment]
Let's start from beginning.
1. Login to`first account`
2. save cookies to your `database` for current `userPk` or `username`
3. Add `new account` but before login, make sure to `clean cookies` _(and for caution, re-create handler again)_
```swift
HTTPCookieStorage.shared.cookies?.forEach({ (cookie) in
    HTTPCookieStorage.shared.deleteCookie(cookie)
})
```
4. `Login` and run `step 2` again
5. whenever you wanted to `switch` between `accounts` you should `clear cookies` again and pass the `cookie` to `handler.login(cache: SessionCache)`

These steps should help you, although I never tried to add multiple accounts by myself.
**Note: Never save cookies (important data) to `userDefaults` because of security reasons.**

**Comment by mkeshnoda** [comment]
I did exactly the same (except that i am saving data with userDefaults 🗡 ) 
But i just did a test on Google Chrome: 
1. I cleared the cookies of instagram
2. I reloaded www.instagram.com and it created cookies on it's own again. ( and ofc cookies were containing logged out user's informations)
I think that's what's happening to me when i am trying to add second user. It creates first user's cookies on its own.

**Comment by mkeshnoda** [comment]
I am doing the same but when i tap on login button it still returns first user's cookies. I delete cookies many times but it doesn't change a thing. 

I tried something with desktop google chrome today. let me explain
I logged out from my account + i deleted all cookies. But when i refreshed instagram my account was still standing there. Maybe that's what's happening to me when i am trying to login with the second account.

**Comment by TheM4hd1** [comment]
Attach the codes here, so we can work on it and find the issue.

**Comment by mkeshnoda** [comment]
`let loginVC = LoginVC()
        self.navigationController?.pushViewController(loginVC, animated: true)
        loginVC.webView.deleteAllCookies()`

**Comment by mkeshnoda** [comment]
Okay, when i want to add account : 
`let loginVC = LoginVC() 
self.navigationController?.pushViewController(loginVC, animated: true)
loginVC.webView.deleteAllCookies()`

Inside LoginVC i have  **var webView = InstagramLoginWebView(frame: .zero)**
`override func viewDidLoad() {
      super.viewDidLoad()
      webView.loadInstagramLogin(isNeedPreloadForCookieSync: false)
      webView.loginDelegate = self
}`

**Inside WebView**

`   @objc func deleteAllCookies() {
        
        print("deleting all cookies")
        self.cleanEveryThing()
        
        fetchCookies { (cookies) in
            for cookie in cookies! {
                self.delete(cookie: cookie)
            }
        }
        
    }`

**Comment by mkeshnoda** [comment]
Okay, when i want to add account :
let loginVC = LoginVC() self.navigationController?.pushViewController(loginVC, animated: true) loginVC.webView.deleteAllCookies()

**Inside LoginVC i have var webView = InstagramLoginWebView(frame: .zero)**
```
override func viewDidLoad() { 
     super.viewDidLoad() webView.loadInstagramLogin(isNeedPreloadForCookieSync: false) 
     webView.loginDelegate = self  
}

```
Inside WebView
```
@objc func deleteAllCookies() {

    print("deleting all cookies")
    self.cleanEveryThing()
    
    fetchCookies { (cookies) in
        for cookie in cookies! {
            self.delete(cookie: cookie)
        }
    }
    
}
```



```
private func login() {

    self.fetchCookies(completion: { (cookies) in
       
        if let cookies = cookies {
            for i in 0..<cookies.count {
                let cookie = cookies[i]
            }
        }
        
        let instagramCookies = cookies?.getInstagramCookies()
        self.isUserLoggedIn(instagramCookies: instagramCookies!)
    })
    
}

```

**Comment by TheM4hd1** [comment]
Every time you call `loadInstagramLogin` function, cookie deleting handled automatically. so you don't need to call it.
set `isNeedPreloadForCookieSync = true` and every time you want to show `webView` do something like this:
```swift
self.loginWebView = nil
self.loginWebView = InstagramLoginWebView(frame: CGRect.zero)
self.view.addSubview(self.loginWebView!)
// setup constraints
self.loginWebView?.loginDelegate = self
self.loginWebView?.loadInstagramLogin(isNeedPreloadForCookieSync: true)
```

If it doesn't help, try to use `Siwa` framework for login for now. and I will double check the web issue.
Tell me if it works.

**Comment by mkeshnoda** [comment]
Still not working...

By the way the other problem is :  
After login, it fetches cookies like  **ds_user_id ** and **csrfToken** BUT it doesn't pass it to `self.isUserLoggedIn(instagramCookies: instagramCookies!)` sometimes. And i don't have any idea why is it happening.

```
private func login() {

    self.fetchCookies(completion: { (cookies) in
       
        if let cookies = cookies {
            for i in 0..<cookies.count {
                let cookie = cookies[i]
            }
        }
        
        let instagramCookies = cookies?.getInstagramCookies()
        self.isUserLoggedIn(instagramCookies: instagramCookies!)
    })
    
}

```

**Comment by TheM4hd1** [comment]
`SwiftyInsta` used `WKCookieWebView` as an embedded browser to handling cookies.
I looked at the [original repo](https://github.com/Kofktu/WKCookieWebView) and it seems it is a known issue and I guess it fixed.
`SwiftyInsta` doesn't use the latest update of the `WKCookieWebView` and I think this is the problem.

As the Author said:

> After running the app, before the first webview was loaded,
> Cookies may not be set properly,
> In that case, use the loader in advance to synchronize.
> ```swift
> WKCookieWebView.preloadWithDomainForCookieSync(urlString: String, completion: (() -> Void)?)
> ```

I guess updating the `WKCookieWebView` will help to fix it.
I'm a little busy for now to doing this update, I'll appreciate if you test it.

**Comment by mkeshnoda** [comment]
Okay, i was able to add second account. But when i am trying to switch between accounts i can't login the account that i am trying to switch in. 

```
public func isUserLoggedIn(instagramCookies : [HTTPCookie]) {
        
        var isLogged = false
        var csrfToken = ""
        

        for i in 0..<instagramCookies.count { 
            let cookie = instagramCookies[i]
            if cookie.name == "ds_user_id" {
                isLogged = true
            }
            
            if cookie.name == "csrftoken" {
                csrfToken = cookie.value
            }
        }

        if isLogged {
            
            let _urlSession = URLSession(configuration: .default)
            let user = SessionStorage.create(username: "username", password: "password")
            
            let instagramHandler = try! APIBuilder()
                .createBuilder()
                .setHttpHandler(urlSession: _urlSession)
                .setRequestDelay(delay: .default)
                .setUser(user: user)
                .build()
        
            let sessionCache = SessionCache.init(user: HandlerSettings.shared.user!, device: HandlerSettings.shared.device!, requestMessage: HandlerSettings.shared.request!, cookies: (instagramCookies.toCookieData()), isUserAuthenticated: true)
            
//            try? instagramHandler.login(cache: sessionCache, completion: { (result) in })

            do {
                
                try instagramHandler.login(cache: sessionCache) { (result) in
                    if  result.isSucceeded {
                        print("\n\n LOGGED IN  \n\n")
                        if self.loginDelegate != nil {
                            self.loginDelegate?.userLoggedSuccessfully()
                        }
                        
                        InstaEndPoint.sharedInstance.handler = instagramHandler

                        self.getUser(instagramCookies: instagramCookies, handler: instagramHandler, csrfToken: csrfToken)
                    } else {
                        print("login failed")
                    }
                }
            } catch {
                print("LOGIN ERROR")
            }
            
        } else { 

        }
        
    }
    
```

**Comment by RealOlympusDev** [comment]
> **Edit:** I'll try it with Siwa and i'll update this comment
> **Edit2:** I can't even login with Siwa framework. It returns `.inccorrectPassword, .invalidUsername` errors..
> 
> Okay, i was able to add second account. But when i am trying to switch between accounts i can't login the account that i am trying to switch in.
> (i pass correct cookies inside `isUserLoggedIn(instagramCookies : [HTTPCookie])` func )
> 
> `try instagramHandler.login(cache: sessionCache) { (result) in`
> `result.isSucceeded` coming as false when i am trying to switch to other account
> 
> ```
> public func isUserLoggedIn(instagramCookies : [HTTPCookie]) {
>         
>         var isLogged = false
>         var csrfToken = ""
>         
> 
>         for i in 0..<instagramCookies.count { 
>             let cookie = instagramCookies[i]
>             if cookie.name == "ds_user_id" {
>                 isLogged = true
>             }
>             
>             if cookie.name == "csrftoken" {
>                 csrfToken = cookie.value
>             }
>         }
> 
>         if isLogged {
>             
>             let _urlSession = URLSession(configuration: .default)
>             let user = SessionStorage.create(username: "username", password: "password")
>             
>             let instagramHandler = try! APIBuilder()
>                 .createBuilder()
>                 .setHttpHandler(urlSession: _urlSession)
>                 .setRequestDelay(delay: .default)
>                 .setUser(user: user)
>                 .build()
>         
>             let sessionCache = SessionCache.init(user: HandlerSettings.shared.user!, device: HandlerSettings.shared.device!, requestMessage: HandlerSettings.shared.request!, cookies: (instagramCookies.toCookieData()), isUserAuthenticated: true)
>             
> //            try? instagramHandler.login(cache: sessionCache, completion: { (result) in })
> 
>             do {
>                 
>                 try instagramHandler.login(cache: sessionCache) { (result) in
>                     if  result.isSucceeded {
>                         print("\n\n LOGGED IN  \n\n")
>                         if self.loginDelegate != nil {
>                             self.loginDelegate?.userLoggedSuccessfully()
>                         }
>                         
>                         InstaEndPoint.sharedInstance.handler = instagramHandler
> 
>                         self.getUser(instagramCookies: instagramCookies, handler: instagramHandler, csrfToken: csrfToken)
>                     } else {
>                         print("login failed")
>                     }
>                 }
>             } catch {
>                 print("LOGIN ERROR")
>             }
>             
>         } else { 
> 
>         }
>         
>     }
>     
> ```

Also having this problem

**Comment by TheM4hd1** [comment]
@mkeshnoda 
@RealOlympusDev 
When you pass the second cookie to `instagramHandler.login(cache: sessionCache)` what is the error when it returns false?
My guess is you are receiving `user must be authenticated.` error.
I faced this error when I was trying to implement this feature.
If you faced this issue, go to `APIHandler.swift` file and comment the `validateLoggedIn` function's body.

Note: make sure to clean build project to apply this change to framework.
If it solved your problem, let me know to release a fix for this function.

**Comment by mkeshnoda** [comment]
I don't remember the error to be honest, i already deleted Siwa framework. Because SwiftyInsta itself was enough, but my multiple account problem is still on the table. For now i just won't add multiple account feature

**Comment by RealOlympusDev** [comment]
I believe I got that error but I also switch back to WebView, I tried the new version of WKWebViewCookie, but I still had to do it twice in order for it to change to the new data

**Comment by TheM4hd1** [comment]
@mkeshnoda this problem is not related to `Siwa`, I believe this is the problem which prevents you to load your cookies.
@RealOlympusDev I know what you're saying, for sure this is WKWebViewCookie problem, because we delete every cookies before requesting new one.
Just try to comment the function I mentioned above, share the results here. I think it will fix your problem.

**Comment by mkeshnoda** [comment]
Yup, Now i don't have any problems with Siwa. which, i am not even use it at the moment. My problem is just; when i logout and login with other user i just can't get new user's cookies. I'll try to fix it again and i can i'll share the solution here.

**Comment by RealOlympusDev** [comment]
@mkeshnoda That would be great. Been trying to fix it for a while lol
@TheM4hd1 Which function? WKCookieWebView.preloadWithDomainForCookieSync(urlString: String, completion: (() -> Void)?)?

**Comment by TheM4hd1** [comment]
> @mkeshnoda That would be great. Been trying to fix it for a while lol
> @TheM4hd1 Which function? WKCookieWebView.preloadWithDomainForCookieSync(urlString: String, completion: (() -> Void)?)?

go to `APIHandler.swift` file and comment the `validateLoggedIn` function's body.

**Comment by RealOlympusDev** [comment]
> > @mkeshnoda That would be great. Been trying to fix it for a while lol
> > @TheM4hd1 Which function? WKCookieWebView.preloadWithDomainForCookieSync(urlString: String, completion: (() -> Void)?)?
> 
> go to `APIHandler.swift` file and comment the `validateLoggedIn` function's body.

Oh, ok

**Comment by RealOlympusDev** [comment]
Fixed it! Had to add a completion handler to webViewFinishedToLoadUser and call self.deleteCookies() on completion of webViewFinishedToLoadUser.

**Comment by RealOlympusDev** [comment]
(This requires the developer to call your completion method at the end of their code)

**Comment by mkeshnoda** [comment]
Did you able to add multiple account feature? @RealOlympusDev

**Comment by mkeshnoda** [comment]
Did you add multiple account feature or something else? @RealOlympusDev

**Comment by RealOlympusDev** [comment]
@mkeshnoda I just have a thing that logs in and out, so when you log out and log back in it doesn’t load the same account anymore.

**Comment by mkeshnoda** [comment]
Can you share your codebase with me please (only necessary parts)  👯‍♂ Because i did a lot of changes in my InstagramLoginWebView. If you want you can send it from anilakkaya58@gmail.com as well

**Comment by TheM4hd1** [comment]
@RealOlympusDev @mkeshnoda 

Any fix?

**Comment by mkeshnoda** [comment]
From my side, no. unfortunately...

**Comment by bullda** [comment]
Same issue, when I want to login another account, the cookie is still the first one, even if I clean all cookies with the codes inside.

**Comment by mkeshnoda** [comment]
I still didn't have time to check it out. I'll probably try it again within a week. I'll keep here updated.

**Comment by mkeshnoda** [comment]
Hi, again @TheM4hd1 

I tried @sbertix 's solution. I was able to login but i can't login automatically when i restart my app.
What i did there was; 
**1-** Saved cookies with user defaults.
**2-** And i passed those cookies into `isUSerLoggedIn(instagramCookies : [HTTPCookie]?)`
Problem : handler is not working. It returns **loginRequired** error.

How can i fix this?

**Comment by sbertix** [comment]
You should not use `isUserLoggedIn(instagramCookies:)`, I left it `public` just because it used to, but it's not supposed to be called like that.
You need to pass the `SessionCache` in the response directly to `handler.login(cache:)`.

**Comment by mkeshnoda** [comment]
Yeah it worked. Grazie mille 💯

**Comment by sbertix** [comment]
Prego 😊 @mkeshnoda

**Comment by sbertix** [comment]
I'm working next on "updating" (most likely just removing) the singleton interface (all the `.shared` `static` properties), in order to make more instances of `APIHandler` (and alia) run in parallel with different users logged in at the same time.
It shouldn't take too long. I hope I can start working on it tomorrow, and if so it should definitely be done by Monday.
So more multi-users stuff coming soon 😊 
@mkeshnoda

**Comment by TheM4hd1** [comment]
@mkeshnoda 
If you succeeded with implementing multiple accounts, please add a note here for others, to prevent re-opening this issue in future.
And make sure to close issue after that.
Regards.

**Comment by mkeshnoda** [comment]
Just completed it. Yeah it worked. Thank you so much guys.   @sbertix  @TheM4hd1
