### ISSUE TITLE
Archived story media feed (archive/reel/day_shells/)

### ISSUE THREAD

**Issue by canaksoy** [TheM4hd1/SwiftyInsta#28]
I added "archive/reel/day_shells/" but I cannot get /feed/reels_media/ with "user_ids" ([archiveDay:18014492728127***])

`{
		"timestamp": 1550275300,
		"media_count": 9,
		"id": "archiveDay:18014492728127***",
		"reel_type": "archive_day_reel",
		"latest_reel_media": 15503425**
	}`

{"message": "Invalid reel id list", "status": "fail"}

**Comment by canaksoy** [comment]
Also needs : /feed/reels_media/

**Comment by TheM4hd1** [comment]
Hello
we found this issue on this topic
https://github.com/TheM4hd1/SwiftyInsta/issues/25#issuecomment-503646557
We couldn’t still find a way, probably something changes in this endpoint 
I can’t give you an exact time, but i’ll work on it.
If you found any solution during this time, let us know
