### ISSUE TITLE
info' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by mzgnr** [TheM4hd1/SwiftyInsta#3]

**Comment by AlexisBarreyat** [comment]
+1

**Comment by TheM4hd1** [comment]
Thanks, I know about access protections issue and I'm going to pull a fix as soon as possible, how ever its simple to fix It your self, change ```struct``` to ```open``` and add a ```public init```

**Comment by mzgnr** [comment]
@TheM4hd1 I'll check issues later today. I also made my fork a Carthage package.

**Comment by AlexisBarreyat** [comment]
Can you add support for caching logged in user , to avoid to login every time the app is launched ?
