### ISSUE TITLE
Is delay (DelayModel) on requests really needed?

### ISSUE THREAD

**Issue by wojczitsu** [TheM4hd1/SwiftyInsta#30]
Do we really need to use delay on requests?

**Comment by TheM4hd1** [comment]
No, it's not necessary, the delay feature implemented for Bots to acts like human when requesting.
For example a Bot can send multiple `like request` in a less time, but this action on humans takes a few seconds(like, scrolling down, wait for loading image, like again).
If you need to speedup your app, you can set the delay to `zero`.
