### ISSUE TITLE
getUserFollowers, getUserFollowing, getUserMedia doesn't return the correct user

### ISSUE THREAD

**Issue by anonrig** [TheM4hd1/SwiftyInsta#31]
Most of the functions like getUserFollowers, getUserFollowing, getUserMedia, etc. first searches for the specific username on the Instagram and then finds the first match and then returns it. 

But the thing is, what happens if I have a commonly used username like "funny" where the search result doesn't bring the actual user with username "funny" but instead returns a different account?

This is an important issue that needs to be addressed. If you need further clarification, I can give full details.

**Comment by TheM4hd1** [comment]
Hello, 
yes this problem reported before, the solution is to receive data by using `userPk`.
The person who reported this issue said he will pull a request very soon for this issue.
But if nothing happenes in a few next days, I'll push an update.

**Comment by TheM4hd1** [comment]
issue fixed in #32

**Comment by anonrig** [comment]
Thanks!
