### ISSUE TITLE
getCurrentUser throws error EXC_BAD_ACCESS after updating from 1.1 to 1.4

### ISSUE THREAD

**Issue by anonrig** [TheM4hd1/SwiftyInsta#33]
I've updated my pod from 1.1 to 1.4

After updating it, getCurrentUser functionality throws error EXC_BAD_ACCESS. Here's the following code:

![Screen Shot 2019-07-05 at 9 24 01 PM](https://user-images.githubusercontent.com/1935246/60739615-53ef0080-9f6b-11e9-930a-a07b01adcd97.png)

This is the place where I run the code (It was working correctly on 1.1)

![Screen Shot 2019-07-05 at 9 25 24 PM](https://user-images.githubusercontent.com/1935246/60739656-71bc6580-9f6b-11e9-9a3a-331572469c1d.png)

**Comment by TheM4hd1** [comment]
if you added framework manually try to remove it from `Linked Libraries and Frameworks`, or if you added it via pod, try to clean build the project and re-build again.

**Comment by anonrig** [comment]
Weird but problem solved. Just curious, do you know the reason behind this?

**Comment by TheM4hd1** [comment]
when you compile a framework, Xcode will use it for next builds, it doesn't re-compile framework every time you build the project(for saving time).
I guess that's the problem, you should force Xcode to compile framework again.

**Comment by anonrig** [comment]
Thanks!
