### ISSUE TITLE
getMediaLikers and getMediaComments not working

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#34]
Hi,

getMediaLikers and getMediaComments methods not working anymore. Before it was working smoothly but now not

**Comment by TheM4hd1** [comment]
Hello,
Just tested these 2 function, it seems they're working fine.
What's the error you got?

**Comment by flamme0011** [comment]
It says EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

this is my code 

self.mediaItems.forEach({ (media) in
                
                do {
                    
                    try self.handler.getMediaLikers(mediaId: media.id!, completion: { (result) in

**Comment by TheM4hd1** [comment]
Clean build your project, if you added framework manually, try to remove it from `General - Linked Libraries and Frameworks`, if you added from pod, just do a clean build.

**Comment by flamme0011** [comment]
nope it is not nil. I tried with cleaning project and it worked. 
Thanks for your help

**Comment by trentona** [comment]
@sbertix  @TheM4hd1 
Im unsure how to use this function. It never seems to live the parameters that I put in.

     handler.media.likers(ofMedia: <#T##String#>, with: <#T##PaginationParameters#>, 
    updateHandler: <#T##PaginationUpdateHandler<User, AnyPaginatedResponse>? 
    ##PaginationUpdateHandler<User, AnyPaginatedResponse>?##(AnyPaginatedResponse, [User], 
    PaginationParameters, [User]) -> Void#>, completionHandler: 
    <#T##PaginationCompletionHandler<User>##PaginationCompletionHandler<User>## 
   (Result<[User], Error>, PaginationParameters) -> Void#>)

It wants a string, Im guessing for the permalink
But all the other info I have no idea what it wants, this is just the autocomplete for the function. Do you have a stand alone version of this function that you could share?

**Comment by trentona** [comment]
@sbertix @TheM4hd1 Do you have a stand alone version of this function that you can share? The auto complete is a little daunting and gives me this. 

    handler.media.likers(ofMedia: <#T##String#>, with: <#T##PaginationParameters#>, 
    updateHandler: <#T##PaginationUpdateHandler<User, AnyPaginatedResponse>? 
    ##PaginationUpdateHandler<User, AnyPaginatedResponse>?##(AnyPaginatedResponse, [User], 
    PaginationParameters, [User]) -> Void#>, completionHandler:   
    <#T##PaginationCompletionHandler<User>##PaginationCompletionHandler<User>## 
    (Result<[User], Error>, PaginationParameters) -> Void#>)

I assume the permalink goes in for the string but past that Im not sure what to do

**Comment by sbertix** [comment]
The first argument is actually the `mediaId` (as represented in `Media.identity.identifier!`).
The `with` `PaginationParameters` adjusts how many pages of data to load.
`updateHandler` is called every time a new page is fetched (`page` is the aggregated `data`, `new` is the paginated array of `User`s, `paginationParameters` is the next `PaginationParameters`, `all` is a concat of all `new` arrays until then.
`completionHandler` is only called once at the end returns a `Result<[User], Error>` `result` and the following `paginationParameters`.

```swift
handler.media.likers(ofMedia: "2145341997261920748",
                                   with: PaginationParameters(startingAt: nil, maxPagesToLoad: 1),
                                   updateHandler: { page, new, paginationParameters, all in },
                                   completionHandler: { result, paginationParameters in })
```

**Comment by trentona** [comment]
ok, cool thank you that makes sense. I only have the permalink though, how do I get the mediaId?
@sbertix
