### ISSUE TITLE
api gets  followers very slowly

### ISSUE THREAD

**Issue by blackjack45** [TheM4hd1/SwiftyInsta#38]
i try to get 4K - 5K followers via your api but it takes too long time.how can i speed this up ? can u have some way to give me all followers like bulk one time ?

**Comment by canaksoy** [comment]
api has DelayModel (random 1-5 sec) you can set lower values. remember that Instagram can block your requests if you send too much. no way to get all one time.

**Comment by blackjack45** [comment]
but this makes my application unusable,How can I improve performance?app starts minimum 2-3  minutes

**Comment by TheM4hd1** [comment]
The efficient way to get followers or similar things is using pagination.
If you want to receive followers page by page, it’s not supported yet.
(for example display 100 user, when scrolled to end, receive next 100 and append to our list) 
Currently the library accepts a maximum number of pages and then returns all extracted  data.
If you want to speedup requests you should set delay to lower values or zero, as our friend mentioned.
