### ISSUE TITLE
[Bug] followUser not working anymore

### ISSUE THREAD

**Issue by wojczitsu** [TheM4hd1/SwiftyInsta#45]
`func followUser(userId: Int, completion: @escaping (Result<FollowResponseModel>) -> ())`
stopped working. There is no error. It just doesn't make us follow the user.

**Comment by sbertix** [comment]
Any more info? What commit are you on?
Cause I can't replicate the issue. It works fine for me.

**Comment by canaksoy** [comment]
seems working for me

**Comment by TheM4hd1** [comment]
attach the info,
it works fine for me.

**Comment by sbertix** [comment]
Any updates? @wojczitsu

**Comment by wojczitsu** [comment]
Sorry, my bad. I was trying to follow private account.
