### ISSUE TITLE
Get Followers Method gives error

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#49]
When I call try handler.getUserFollowers(userId: userId, maxId: nextPageId, searchQuery: "", completion: { (result, maxId) 

after 298 nd request its gaves error like:

Result<UserShortListModel>(isSucceeded: false, info: SwiftyInsta.ResultInfo(error: SwiftyInsta.CustomErrors.noError, message: "The operation couldn’t be completed. (SwiftyInsta.CustomErrors error 9.)", responseType: SwiftyInsta.ResponseTypes.wrongRequest), value: nil)

PS: I already remove delay. With delay method it is working

**Comment by sbertix** [comment]
Instagram Private API are not intended to _"spam"_ requests, cause they should only be called after user interaction.
It's most likely just Instagram telling you you've made too many requests.
Delay has been implemented to avoid exactly that.

**Comment by TheM4hd1** [comment]
That's because of Instagram rate limit, we warned you about this before.
As @sbertix said, the API designed to work with user interaction. So a rate limit error raised when you sen these number of requests.
