### ISSUE TITLE
Tags Users on Photo upload. 

### ISSUE THREAD

**Issue by migueliOS** [TheM4hd1/SwiftyInsta#5]
I've seen this feature available for Instagram-API-Python on a PR. Maybe it could be done for Swift as well. 

I tried several combinations of the payload like
`usertags: [{ user_id: 0000, x: 0.1, y 0.1}]`
`usertags: [{ user_id: 0000, position: [0.1,0.1]}]`

But none of my combinations work. Maybe it needs an extra step that I cannot see right now that I just starting using this library.

**Comment by TheM4hd1** [comment]
```editMedia``` feature has been added(just for editing caption) and I think its possible to add tags with this function which sends data to ```/media/MEDIA_ID/edit_media/```
As I know the ```x, y``` values should be in a range of ```0...1```, and ```user_id``` must be a ```string``` (or maybe I'm wrong)

Here is a part of response for ```editMedia``` feature:
```
 "usertags": {
    "in": [
    {
        "user": {
        "pk": 9529571412,
        "username": "swifty.tips",
        "full_name": "",
        "is_private": false,
        "profile_pic_url": "https://scontent-iad3-1.cdninstagram.com/vp/48cfafac6ec613cc688ad958fa4b55f2/5CB64CF1/t51.2885-19/44884218_345707102882519_2446069589734326272_n.jpg?_nc_ht=scontent-iad3-1.cdninstagram.com",
        "is_verified": false
        },
        "position": [
        0.8200000000000001,
        0.5822556391
        ],
        "start_time_in_video_in_sec": null,
        "duration_in_video_in_sec": null
    }
          ]
}
```

Im kind of busy right now but I will try to implement it as soon as possible. If you find out anything that could helps, share it and we will work on it.

**Comment by migueliOS** [comment]
Cool, I will give a try with edit media and see if it could help in the process. Thanks!

**Comment by TheM4hd1** [comment]
The feature has been tested and works fine. let me know if there is any question.

please look at the test before using it.
https://github.com/TheM4hd1/SwiftyInsta/blob/bc66474b038d9559665eec199a41adbeb896139a/SwiftyInstaTests/SwiftyInstaTests.swift#L792

**Comment by migueliOS** [comment]
Awesome, will test it asap and let you know. Thanks 🙏
