### ISSUE TITLE
Adding Travis CI support

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#56]
I feel like implementing `Travis CI` might be a good idea, especially with all the changes that are being discussed for `2.0`.
Just an opinion though.

**Comment by TheM4hd1** [comment]
`Travis CI` added in `development` branch for `2.0`
https://github.com/TheM4hd1/SwiftyInsta/commit/c693417af24ae60b1ccffc50e51753b523992a87
