### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by greatsk55** [TheM4hd1/SwiftyInsta#6]
I tried to login and it failed.   failed message is "too many HTTP redirects"

**Comment by TheM4hd1** [comment]
Did you have this issue from start? or after a few logins you got this error ?
In this case clearing ```shared cookies``` can help.

```
// Clearing saved cookies before login.
HTTPCookieStorage.shared.cookies?.forEach({ (cookie) in
    HTTPCookieStorage.shared.deleteCookie(cookie)
})
```

Run a test and see if it works.
https://github.com/TheM4hd1/SwiftyInsta/blob/bca0f174d958650fb1252e4df463c793d11a0986/SwiftyInstaTests/SwiftyInstaTests.swift#L39

**Comment by ankitsiliconithub** [comment]
Tried to Login with example code and getting this Result

Result<LoginResultModel>(isSucceeded: false, info: SwiftyInsta.ResultInfo(error: SwiftyInsta.CustomErrors.challengeRequired, message: "The operation couldn’t be completed. (SwiftyInsta.CustomErrors error 6.)", responseType: SwiftyInsta.ResponseTypes.ok), value: Optional(SwiftyInsta.LoginResultModel.challengeRequired))

What'd be the issue !!

**Comment by TheM4hd1** [comment]
Your account needs to verify a challenge before login.
There is also an example to login with challenge in tests.


________________________________

**Comment by TheM4hd1** [comment]
Your account needs to verify a challenge before login.
There is also an example to login with challenge in tests.

https://github.com/TheM4hd1/SwiftyInsta/blob/bca0f174d958650fb1252e4df463c793d11a0986/SwiftyInsta/API/Services/APIHandler.swift#L54

https://github.com/TheM4hd1/SwiftyInsta/blob/bca0f174d958650fb1252e4df463c793d11a0986/SwiftyInsta/API/Services/APIHandler.swift#L58

> Re: [TheM4hd1/SwiftyInsta] login failed (#6)
> 
> ankitsiliconithub <notifications@github.com>
> Thu 1/10/2019, 10:36 AM
> You; TheM4hd1/SwiftyInsta; Comment
> 
> Tried to Login with example code and getting this Result
> 
> Result(isSucceeded: false, info: SwiftyInsta.ResultInfo(error: SwiftyInsta.CustomErrors.challengeRequired, message: "The operation couldn’t be completed. (SwiftyInsta.CustomErrors error 6.)", responseType: SwiftyInsta.ResponseTypes.ok), value: Optional(SwiftyInsta.LoginResultModel.challengeRequired))
> 
> What'd be the issue !!

**Comment by greatsk55** [comment]
Thank you. I tried it as you said, but I got error.

> The operation couldn’t be completed. (SwiftyInsta.CustomErrors error 1.)

**Comment by TheM4hd1** [comment]
Please explain your steps, (what did you do exactly) and cast error to ```CustomErrors``` so we can understand what the real issue is.
if this is a ```runTimeError(string)```, don't forget to print the ```localizedString```
Probably your doing a mistake or there is something wrong with your account, just make sure everything is fine.
