### ISSUE TITLE
Story Viewers Pagination

### ISSUE THREAD

**Issue by TolgaKaramese** [TheM4hd1/SwiftyInsta#66]

**Comment by sbertix** [comment]
I've pushed a PR addressing the issue. @TolgaKaramese

**Comment by TolgaKaramese** [comment]
@sbertix I opened this issue due to Mahdi's request :)

**Comment by sbertix** [comment]
Hahahaha okay 😊 still, the PR is there 🙈

**Comment by TolgaKaramese** [comment]
Okay, thanks ☺️
