### ISSUE TITLE
Adding tags to GitHub repo page

### ISSUE THREAD

**Issue by sbertix** [TheM4hd1/SwiftyInsta#71]
I thought of maybe adding some tags to the repository for easier discoverability.
Something like **#swift**, **#instagram**, **#api**, **#cocoapods** or sth along these lines… idk.
What do you think? @TheM4hd1 

And I would also consider moving the _url_ to the `README`. It feels misplaced in the description, imho. But it's just an opinion though.

**Comment by TheM4hd1** [comment]
Done.
if you suggest more topics let me know.
