### ISSUE TITLE
Missing Followers

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#73]
When I call handler.getUser function it returns 12710 and it is correct but when I call
handler.getUserFollowers returns 12702.  8 user are missing.

**Comment by TheM4hd1** [comment]
Attach the code and the account you are testing with.

**Comment by sbertix** [comment]
Hey @flamme0011 

This is an issue with how Instagram handles deactivated, reported, fake accounts, etc.

Followers/following count does not represent the actual exact active accounts following/followed by you at any given time: it gets close to it but it is not supposed to be the actual figure. Instagram does not update it every time it's requested, it simply adds and removes users with further interactions (e.g. follow "somebody", add +1, block "somebodyelse", -1, etc.). 

Fake accounts, etc. are only periodically checked and the counters updated, but there's nothing we can do to fix it or force a refresh, unfortunately. So especially with larger account, you'll definitely see a 1%-5% (according to testing) difference.
