### ISSUE TITLE
Multiple Account Login Problem

### ISSUE THREAD

**Issue by mkeshnoda** [TheM4hd1/SwiftyInsta#79]
@sbertix `func isUserLoggedIn(instagramCookies : [HTTPCookie]?)`  recieves only 2 cookies. That's the reason why it doesn't login. And when it recieves 6 cookies, it works.  It's just a matter of luck 😄 

Here is my flow
```
var webView: InstagramLoginWebView? {
        didSet {
            oldValue?.removeFromSuperview()
            guard let webView = webView else { return }
            view.addSubview(webView)
            // always request log in page when setting a new web view.
            webView.loadInstagramLogin()
            webView.fillToSuperview()
        }
    }
```

```
override func viewDidLoad() {
        super.viewDidLoad()


         InstagramLoginWebView.create(with: self.view.bounds, didReachEndOfLoginFlow: nil, 
                  didSuccessfullyLogIn: {
                          self.showProfileVC()
                  }, completionHandler: { (cache, handlerProtocol) in
                           //do stuff
                 }, returnHandler: {[weak self] in self?.webView = $0 })

}

```

**Comment by sbertix** [comment]
Do you mind telling me the `name`s alone of the `HTTPCookie`s in the `cookies` property in row 122, and the value of `startedAt` in the next one? @mkeshnoda

**Comment by sbertix** [comment]
Thing is… since it no longer checks for a specific `URL`, that method is called several times to account for login cookies. So at different times they surely have different amount of cookies.
I just need the one at the end of the flow, once the timeline is shown, when the login has finished.

**Comment by mkeshnoda** [comment]
> Do you mind telling me the `name`s alone of the `HTTPCookie`s in the `cookies` property in row 122, and the value of `startedAt` in the next one? @mkeshnoda

My bad sorry. This time, i recieved  `csrftoken` and `mid`

**Comment by sbertix** [comment]
No `ds_user_id` and `sessionid`?  🧐
Yet you still manage to complete the login flow and the timeline is loaded fine in the `webView` after you've completed the login steps, correct?

**Comment by mkeshnoda** [comment]
> No `ds_user_id` and `sessionid`? 🧐
> Yet you still manage to complete the login flow and the timeline is loaded fine in the `webView` after you've completed the login steps, correct?

Si. I can't recieve these two them most of the time. When i do everything works very well. 
Btw yes i can see my instagram timeline in the webView.

**Comment by sbertix** [comment]
What do you mean by "when I do everything works very well"?
Cause, again: without those three cookies you're not actually logged in… so it means you just need to keep going with what's on screen (a challenge, a "skip" button, etc…) until you reach the timeline (in this case) or the first page when it detects all cookies.

This behaviour hasn't changed from previous versions, plus you wouldn't have been able to log in either without a `ds_user_id` cookie. So, I can't really see the problem here…
I've tested it with 4 different accounts and it works just like before: you get to the end and you're logged in, you don't get to the end, you're not logged in 😊

**Comment by mkeshnoda** [comment]
> What do you mean by "when I do everything works very well"?
> Cause, again: without those three cookies you're not actually logged in… so it means you just need to keep going with what's on screen (a challenge, a "skip" button, etc…) until you reach the timeline (in this case) or the first page when it detects all cookies.
> 
> This behaviour hasn't changed from previous versions, plus you wouldn't have been able to log in either without a `ds_user_id` cookie. So, I can't really see the problem here…
> I've tested it with 4 different accounts and it works just like before: you get to the end and you're logged in, you don't get to the end, you're not logged in 😊

i mean, when i recieve `ds_user_id` ,  `csrftoken` , `sessionid` everything works. Problem is i can't recieve those cookies 😄

**Comment by sbertix** [comment]
> i mean, when i recieve `ds_user_id` , `csrftoken` , `sessionid` everything works. Problem is i can't recieve those cookies 😄

Hahaha okay… unfortunately 100% not an issue with **SwiftyInsta** though ☹️ 
Sorry I can't help more than this.
