### ISSUE TITLE
Need to upload video

### ISSUE THREAD

**Issue by alokfuterox** [TheM4hd1/SwiftyInsta#8]
I need to upload video to Instagram. Please let me know how can I do it.

Thanks 
Alok

**Comment by TheM4hd1** [comment]
```uploadVideo``` feature has been removed from library because of an unknown issue.
it just stoped working and I couldn't find the problem, feel free to contribute
For now just ```uploadPhoto``` and ```uploadPhotoAlbum``` are available.

**Comment by TheM4hd1** [comment]
The feature has been tested and works fine, if you have any question, please let me know
Make sure you read the test before using it.
https://github.com/TheM4hd1/SwiftyInsta/blob/be9289b8b9279f1f6f004e5cbc649cb6d98d8a92/SwiftyInstaTests/SwiftyInstaTests.swift#L704
