### ISSUE TITLE
Problem while getting handler.users.recentActivities

### ISSUE THREAD

**Issue by hknckr** [TheM4hd1/SwiftyInsta#85]
Hi, 
I have got error while getting users.recentactivities response. I am using pod version 2.01 (latest for now)

I am new to the library may be I am doing something wrong or the response is not valid I am not sure yet so I decided to create an issue for that.

**In short it says : Expected to decode Data but found a dictionary instead.**

Do i need to make another variable  different than result in completionhandler or response is not valid in the library?

Here is my code and the error I got ; 
(I have already authenticated and I can get followers list without any problem)

```
handler.users.recentActivities(
                                   with: .init(maxPagesToLoad: .max),
                                   updateHandler: nil,
                                   completionHandler: {result, _ in
                                    
                                  print(result)
})
```

When i add breakpoint at print line I can see a failure and error ;

Printing description of result:
▿ Result<Array<RecentActivitiesModel>, Error>
  ▿ failure : DecodingError
    ▿ typeMismatch : 2 elements
      - .0 : Foundation.Data
      ▿ .1 : Context
        ▿ codingPath : 4 elements
          - 0 : CodingKeys(stringValue: "aymf", intValue: nil)
          - 1 : CodingKeys(stringValue: "items", intValue: nil)
          ▿ 2 : _JSONKey(stringValue: "Index 0", intValue: 0)
            - stringValue : "Index 0"
            ▿ intValue : Optional<Int>
              - some : 0
          - 3 : CodingKeys(stringValue: "user", intValue: nil)
        - debugDescription : "Expected to decode Data but found a dictionary instead."
        - underlyingError : nil

**Comment by sbertix** [comment]
I'm pushing a fix asap. @hknckr 
Thanks 💪
