### ISSUE TITLE
Follower/Following Count in User function

### ISSUE THREAD

**Issue by flamme0011** [TheM4hd1/SwiftyInsta#89]
Are Follower/Following/Media count remove from user function?
I am calling 

handler.users.user(.me, completionHandler: { (result) in

bu can not get the count of the follower, following and media in the latest version

**Comment by TheM4hd1** [comment]
we have dynamic responses right now which means you can access every single value contained in the returned JSON.

```swift
let _pk: Int = ...
handler.users.user(.primaryKey(_pk)) { (user) in
    let a = try! user.get()?.rawResponse.followerCount
    print(a?.int)
}

```
