### ISSUE TITLE
Get User Tags

### ISSUE THREAD

**Issue by blackjack45** [TheM4hd1/SwiftyInsta#90]
when i get media which users taged from old version,i used this method

>   self.handler.getUserTags

but i couldnt find similar method in new version.How can i get user tags ?

**Comment by sbertix** [comment]
You can use 

```swift
self.handler.users.tagged(user: /* the reference to the user */,
                                            with: /* the pagination parameter */,
                                            updateHandler: { _, _, _, _ in },
                                            completionHandler: { _, _ in })
```

The reference can be either `.me`, `.primaryKey(/* the primary key of the user */)`, `.username(/* the username of the user*)`.
