### ISSUE TITLE
  i want get all story viewers (  new version )

### ISSUE THREAD

**Issue by blackjack45** [TheM4hd1/SwiftyInsta#91]
How can i get all story viewers one time ? if cannot get one time, should i do nested for loop ?one of for stories one of viewers in one story.

**Comment by sbertix** [comment]
You can pass `.init(maxPagesToLoad: .max)` as `PaginationParameters`, and then listen to the `updateHandler`'s response.

**Comment by blackjack45** [comment]
No no i mean,i want get all stories and viewers bulk same time in one model.Is it possible ?

**Comment by sbertix** [comment]
Unfortunately it's not.
The endpoints for stories and viewers are different. So you have to ask first for stories, and then ask for related viewers.

**Comment by blackjack45** [comment]
hımm ok thank you :)
