### ISSUE TITLE
Media Type

### ISSUE THREAD

**Issue by barley0** [TheM4hd1/SwiftyInsta#92]
Hi,
Thanks for this great Api.

I am try to understand if media is photo, video or carouselMedia. I can see in debugger but I can not check in if statement.

My code:

     self.handler.media.by(user: .me, with: .everything, updateHandler: nil, completionHandler: {(result, page) in
            
            let mediaResult = try! result.get()            
            mediaResult.forEach({(item) in
                
How can I check item.content is photo, video or carouselMedia?
                if item.content == ??????{
                    
                }                
            })            
        })

**Comment by sbertix** [comment]
`mediaResult` is of type `Array<Media>`. So you can enumerate them like you did and then, through the `.content` accessory assess what whether they're pics, vids or albums.

``` swift
mediaResult.forEach { item in
	switch item.content {
	case .picture(let picture): /* do sth */
	case .video(let video): /* do sth */
	case .alum(let album):
		album.forEach {
			switch $0 {
			case .picture(let picture): /* do sth */
			case .video(let video): /* do sth */
			default: break /* it should never be called */
			}
		}
	}
}
```
